const {chromium}=require('playwright');const fs=require('fs');
const http=require('http'),path=require('path'); const server=http.createServer((req,res)=>{let f=path.resolve('teachers','.'+decodeURIComponent(req.url.split('#')[0].split('?')[0]));if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');try{res.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.json')?'application/json':f.endsWith('.mp3')?'audio/mpeg':f.endsWith('.webp')?'image/webp':f.endsWith('.png')?'image/png':'text/html');res.end(fs.readFileSync(f));}catch{res.statusCode=404;res.end('missing')}});
(async()=>{await new Promise(r=>server.listen(8765,r));const b=await chromium.launch({headless:true,executablePath:process.env.BOOST_CHROMIUM,args:['--autoplay-policy=no-user-gesture-required']});const context=await b.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8765/grade6/boost-simulation/');await p.waitForSelector('.slide');await p.evaluate(()=>document.fonts.ready);const slides=JSON.parse(fs.readFileSync('teachers/grade6/boost-simulation/lesson.json'));const report={slides:slides.length,sizes:[],touch:[],audio:[]};
for(const size of [{width:360,height:640},{width:390,height:844},{width:1024,height:640},{width:844,height:390}]){await p.setViewportSize(size);let hor=0,pairs=0,maxScroll=0;for(let i=0;i<slides.length;i++){await p.evaluate(i=>show(i),i);const r=await p.evaluate(()=>{const s=deck.children[at],c=s.querySelector('.content'),box=c.getBoundingClientRect();return {hor:Math.max(document.documentElement.scrollWidth-innerWidth,c.scrollWidth-c.clientWidth),scroll:s.scrollHeight-s.clientHeight,box:{x:box.x,y:box.y,width:box.width,height:box.height},q:s.querySelector('.q')?.getBoundingClientRect().toJSON(),opts:[...s.querySelectorAll('.option')].map(e=>e.getBoundingClientRect().toJSON())}});if(r.box.y<40)throw Error('top clipping '+i+' '+size.width+' '+r.box.y);if(r.hor>1)throw Error(`horizontal ${i} ${size.width} ${r.hor}`);maxScroll=Math.max(maxScroll,r.scroll);if(slides[i].kind==='mcq'&&!slides[i].reveal){await p.evaluate(i=>show(i+1),i);const r2=await p.evaluate(()=>({q:deck.children[at].querySelector('.q').getBoundingClientRect().toJSON(),opts:[...deck.children[at].querySelectorAll('.option')].map(e=>e.getBoundingClientRect().toJSON())}));if(JSON.stringify(r.q)!==JSON.stringify(r2.q)||JSON.stringify(r.opts)!==JSON.stringify(r2.opts))throw Error('pair moves '+i);pairs++;} }report.sizes.push({...size,pairs,maxScroll});}
await p.setViewportSize({width:390,height:844});const cdp=await context.newCDPSession(p);
async function swipe(x,y,dx,dy){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let k=1;k<=10;k++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*k/10,y:y+dy*k/10}]});await p.waitForTimeout(15)}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(250);}
const q=slides.findIndex(s=>s.kind==='mcq');for(const [name,dx,dy,expected] of [['up',0,-160,1],['down',0,160,-1],['left',-160,0,1],['right',160,0,-1]]){await p.evaluate(i=>show(i),q+1);await swipe(240,350,dx,dy);let at=await p.evaluate(()=>window.at??Number(document.querySelector('#jump').value));if(at!==q+1+expected)throw Error('touch '+name+' '+at);report.touch.push(name);}
await p.evaluate(i=>show(i),q);await swipe(240,350,0,-160);await swipe(240,350,0,-160);if(Number(await p.locator('#jump').inputValue())!==q+2)throw Error('Q answer next');report.touch.push('question-answer-next');
const pic=slides.findIndex(s=>s.kind==='picture');await p.evaluate(i=>show(i),pic);await swipe(190,150,-130,0);if(Number(await p.locator('#jump').inputValue())!==pic+1)throw Error('image swipe');report.touch.push('image');
const model=slides.findIndex(s=>s.kind==='storymodel');await p.setViewportSize({width:360,height:640});await p.evaluate(i=>show(i),model);let before=Number(await p.locator('#jump').inputValue());await swipe(240,470,0,-170);if(Number(await p.locator('#jump').inputValue())!==before)throw Error('scroll skips slide');report.touch.push('long-slide-scroll');await p.evaluate(()=>{deck.children[at].scrollTop=deck.children[at].scrollHeight});await swipe(240,450,0,-170);if(Number(await p.locator('#jump').inputValue())!==model+1)throw Error('scroll edge swipe');report.touch.push('scroll-edge');
await p.waitForTimeout(400);const audio=JSON.parse(fs.readFileSync('teachers/grade6/boost-simulation/audio-texts.json'));for(const key of Object.keys(audio)){const i=slides.findIndex(s=>s.audio===key);await p.evaluate(i=>show(i),i);await p.locator(`.slide:not([hidden]) [data-audio="${key}"]`).click();await p.waitForTimeout(450);const r=await p.evaluate(()=>({time:player?.currentTime,duration:player?.duration,paused:player?.paused}));if(!(r.time>0&&r.duration>0&&!r.paused))throw Error('audio '+key+JSON.stringify(r));report.audio.push({key,...r});await p.evaluate(()=>show(at+1));if(await p.evaluate(()=>player!==null))throw Error('audio continues');}
await p.setViewportSize({width:1024,height:640});await p.evaluate(i=>show(i),q+1);await p.screenshot({path:'boost-answer.png'});await p.evaluate(i=>show(i),slides.findIndex(s=>s.kind==='story'));await p.screenshot({path:'boost-story.png'});await p.setViewportSize({width:360,height:640});await p.evaluate(i=>show(i),q+1);await p.screenshot({path:'boost-mobile.png'});await p.goto('http://127.0.0.1:8765/#grade6');await p.locator('a.material[href="grade6/boost-simulation/"]').click();await p.waitForSelector('.slide');await p.locator('.home').click();await p.waitForURL('**/#grade6');if(!await p.locator('#grade6').isVisible())throw Error('home');report.errors=errors;if(errors.length)throw Error(errors.join(','));fs.writeFileSync('teachers/grade6/boost-simulation/qa-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await b.close();server.close();})();
