(()=>{'use strict';
const $=s=>document.querySelector(s),D=READING,audio=$('#audio'),stage=$('#stage'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const speedKey='teachers-read-alone-speed-v1',progressKey='teachers-unit2-reading-v1',speeds=[1,.75,.5,.35,.25];
let textIndex=0,mode='parts',pos=0,run=0,timer=0,frame=0,clip=null,active=-1,tipTarget=null,finished=false;const completed=new Set();
const params=new URLSearchParams(location.search);let saved={};try{saved=JSON.parse(localStorage.getItem(progressKey)||'{}');}catch(e){}
if(params.has('text'))textIndex=Math.max(0,D.texts.findIndex(t=>t.id===params.get('text')));else{textIndex=Math.min(D.texts.length-1,Math.max(0,Number(saved.textIndex)||0));mode=saved.mode==='sentences'?'sentences':'parts';pos=Math.max(0,Number(saved.pos)||0);}
if(params.get('mode')==='sentences')mode='sentences';
let speed=.75;try{const n=Number(localStorage.getItem(speedKey));if(speeds.includes(n))speed=n;}catch(e){}
function applySpeed(n){speed=speeds.includes(n)?n:.75;audio.defaultPlaybackRate=audio.playbackRate=speed;audio.preservesPitch=true;$('#speed').value=String(speed);}applySpeed(speed);
const current=()=>D.texts[textIndex],count=()=>mode==='parts'?current().pages.length:current().ids.length*2;
const ids=()=>mode==='parts'?current().pages[pos].ids:[current().ids[Math.floor(pos/2)]];
function hideTip(){tipTarget?.removeAttribute('aria-describedby');tipTarget=null;$('#tooltip').hidden=true;}
function showTip(target){hideTip();tipTarget=target;const tip=$('#tooltip');tip.textContent=target.dataset.he;tip.hidden=false;target.setAttribute('aria-describedby','tooltip');const a=target.getBoundingClientRect(),b=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(innerWidth-b.width-8,a.left+(a.width-b.width)/2))+'px';tip.style.top=(a.top-b.height-8>=4?a.top-b.height-8:a.bottom+8)+'px';}
function clear(){document.querySelectorAll('.current').forEach(w=>w.classList.remove('current'));active=-1;}
function stop(){run++;clearTimeout(timer);cancelAnimationFrame(frame);audio.pause();clear();$('#play').textContent='▶ Play';}
function clock(t){return `${Math.floor(Math.max(0,t)/60)}:${String(Math.floor(Math.max(0,t)%60)).padStart(2,'0')}`;}
function bounds(selected=ids()){const ss=selected.map(n=>D.sentences[n]);return {src:ss[0].audio,start:ss[0].start,end:ss.at(-1).end,words:ss.flatMap(s=>(s.timings||[]).map((w,j)=>({...w,key:`${s.id}-${j}`})))};}
function sync(){if(!clip)return;const time=audio.currentTime;$('#time').textContent=clock(time-clip.start);$('#seek').value=Math.max(0,time-clip.start);if(audio.paused){clear();return;}const n=clip.words.findIndex(w=>time>=w.start&&time<w.end);if(n!==active){clear();active=n;if(n>=0){const el=$(`[data-key="${clip.words[n].key}"]`);el?.classList.add('current');if(el){const a=el.getBoundingClientRect(),b=stage.getBoundingClientRect();if(a.top<b.top||a.bottom>b.bottom)el.scrollIntoView({block:'center',behavior:'instant'});}}}if(time>=clip.end+.025){audio.pause();finished=true;completed.add(current().id+'-'+mode+'-'+pos);$('#next').classList.add('ready');$('#status').textContent='Part complete. Continue when ready.';}}
async function play(restart=false,selected=ids()){
 const before=clip&&audio.currentTime;stop();finished=false;$('#next').classList.remove('ready');clip=bounds(selected);const mine=run;
 if(!clip.src||!clip.words.length){$('#status').textContent='Audio is not available yet.';return;}
 const src=new URL(clip.src,location.href).href;if(audio.src!==src){audio.src=src;audio.load();}
 try{if(audio.readyState<1)await new Promise((resolve,reject)=>{const ok=()=>{cleanup();resolve();},bad=()=>{cleanup();reject(Error('Audio unavailable'));},timeout=setTimeout(bad,10000);function cleanup(){clearTimeout(timeout);audio.removeEventListener('loadedmetadata',ok);audio.removeEventListener('error',bad);}audio.addEventListener('loadedmetadata',ok,{once:true});audio.addEventListener('error',bad,{once:true});});if(mine!==run||document.hidden||$('#menu').open)return;
  audio.currentTime=restart||before===null||before===undefined||before<clip.start||before>=clip.end?Math.max(0,clip.start-.025):before;applySpeed(speed);await audio.play();if(mine!==run){audio.pause();return;}$('#play').textContent='❚❚ Pause';$('#status').textContent='Listen and follow the yellow word.';function watch(){if(mine!==run)return;sync();if(!audio.paused)frame=requestAnimationFrame(watch);}watch();
 }catch(e){if(mine===run)$('#status').textContent='Choose Play to start the recording.';}
}
function wordHTML(s,j,individual){const w=s.words[j];return `<span class="word" data-key="${s.id}-${j}" ${individual?`tabindex="0" role="button" data-he="${esc(w.he)}" aria-label="${esc(w.word)}: Hebrew meaning"`:''}>${esc(w.word)}</span>`;}
function sentenceHTML(s){if(mode==='sentences')return s.words.map((w,j)=>wordHTML(s,j,true)).join(' ');return s.units.map(u=>`<span class="unit" tabindex="0" role="button" data-he="${esc(u.he)}" aria-label="Hebrew meaning">${s.words.slice(u.start,u.end).map((w,j)=>wordHTML(s,u.start+j,false)).join(' ')}</span>`).join(' ');}
function render(){stop();hideTip();pos=Math.min(count()-1,Math.max(0,pos));stage.scrollTop=0;const t=current(),selected=ids(),ss=selected.map(n=>D.sentences[n]),reveal=mode==='sentences'&&pos%2===1;clip=bounds();finished=false;
 $('#position').textContent=`${pos+1} / ${count()}`;$('#parts').setAttribute('aria-pressed',String(mode==='parts'));$('#sentences').setAttribute('aria-pressed',String(mode==='sentences'));
 $('#tabs').hidden=mode!=='parts';$('#tabs').innerHTML=mode==='parts'?t.pages.map((p,n)=>`<button id="tab-${n}" role="tab" aria-controls="page" aria-selected="${n===pos}" data-page="${n}" class="${completed.has(t.id+'-parts-'+n)?'done':''}" aria-label="Part ${n+1}: ${esc(p.title)}">${n+1}</button>`).join(''):'';
 $('#page').className=mode==='sentences'?'sentence':'part';$('#page').setAttribute('role','tabpanel');$('#page').setAttribute('aria-label',mode==='parts'?t.pages[pos].title:'Sentence '+(Math.floor(pos/2)+1));
 const photo=t.photo&&mode==='parts'?`<figure><img src="../${esc(t.photo.file)}" alt="${esc(t.photo.alt)}"><figcaption>${esc(t.photo.caption)}</figcaption></figure>`:'';
 const sourceLinks=t.sources.map((u,n)=>`<li><a href="${esc(u)}" target="_blank" rel="noopener">${new URL(u).hostname.replace(/^www\./,'')} · Source ${n+1}</a></li>`).join('');
 $('#page').innerHTML=`<h1>${esc(mode==='parts'?t.pages[pos].title:t.title)}</h1><p class="period">${esc(t.period)}</p><div class="reading-layout"><div class="text" lang="en">${ss.map(s=>`<p data-sentence="${s.id}">${sentenceHTML(s)}</p>`).join('')}</div>${photo}</div>${mode==='sentences'?`<p class="translation ${reveal?'':'hidden'}" lang="he" dir="rtl" ${reveal?'':'aria-hidden="true"'}>${esc(ss[0].he)}</p>`:`<details><summary>תרגום לעברית</summary><div class="translation" lang="he" dir="rtl">${ss.map(s=>esc(s.he)).join(' ')}</div></details><details class="sources"><summary>Sources & credits</summary><ul class="source-list">${sourceLinks}</ul><p>Adapted for English learners. Narration describes the documented period. ${t.photo?esc(t.photo.caption):''}</p></details>`}`;
 $('#previous').disabled=pos===0;$('#next').textContent=pos===count()-1?'Next text →':'Continue →';$('#next').disabled=pos===count()-1&&textIndex===D.texts.length-1;$('#next').classList.remove('ready');$('#status').textContent=mode==='sentences'?'The sentence plays after two seconds.':'Choose Play to listen.';
 $('#seek').max=Math.max(.1,(clip.end||0)-(clip.start||0));$('#seek').value=0;$('#duration').textContent=clock(Number($('#seek').max));$('#time').textContent='0:00';
 document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>go(Number(b.dataset.page)));
 document.querySelectorAll('[data-he]').forEach(w=>{w.onpointerenter=e=>{if(e.pointerType!=='touch')showTip(w);};w.onpointerleave=e=>{if(e.pointerType!=='touch')hideTip();};w.onfocus=()=>showTip(w);w.onblur=hideTip;w.onclick=()=>showTip(w);w.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();showTip(w);}};});
 try{localStorage.setItem(progressKey,JSON.stringify({textIndex,mode,pos}));}catch(e){}
 if(mode==='sentences'&&clip.src)timer=setTimeout(()=>play(true),2000);
}
function go(n){pos=Math.max(0,Math.min(count()-1,n));render();}
function step(d){if(d>0&&pos===count()-1&&textIndex<D.texts.length-1){textIndex++;pos=0;render();}else go(pos+d);}
function chooseText(n){textIndex=n;pos=0;$('#menu').close();render();}
$('#play').onclick=()=>audio.paused?play(finished):stop();$('#repeat').onclick=()=>{const ss=ids().map(n=>D.sentences[n]),s=ss.find(s=>audio.currentTime>=s.start&&audio.currentTime<=s.end)||ss[0];play(true,[s.id]);};
$('#restart').onclick=()=>{pos=0;render();play(true);};$('#previous').onclick=()=>step(-1);$('#next').onclick=()=>{step(1);if(mode==='parts')play(true);};
$('#parts').onclick=()=>{mode='parts';pos=0;render();};$('#sentences').onclick=()=>{mode='sentences';pos=0;render();};$('#speed').onchange=e=>{applySpeed(Number(e.target.value));try{localStorage.setItem(speedKey,String(speed));}catch(e){}};
$('#seek').oninput=e=>{const wasPlaying=!audio.paused;clearTimeout(timer);clip=bounds();const src=new URL(clip.src,location.href).href;if(audio.src!==src)audio.src=src;audio.currentTime=clip.start+Number(e.target.value);finished=false;$('#next').classList.remove('ready');sync();if(wasPlaying&&audio.paused)play();};
$('#menuButton').onclick=()=>{stop();$('#menu').showModal();};$('#closeMenu').onclick=()=>$('#menu').close();$('#textList').innerHTML=D.texts.map((t,n)=>`<button data-text="${n}">${esc(t.title)}<br><span class="small">${esc(t.period)}</span></button>`).join('');document.querySelectorAll('[data-text]').forEach(b=>b.onclick=()=>chooseText(Number(b.dataset.text)));
audio.addEventListener('pause',()=>{clear();$('#play').textContent='▶ Play';});audio.addEventListener('timeupdate',sync);audio.addEventListener('ended',()=>{clear();finished=true;$('#next').classList.add('ready');});
document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);stage.addEventListener('scroll',hideTip,{passive:true});window.addEventListener('resize',hideTip);document.addEventListener('pointerdown',e=>{if(!e.target.closest('[data-he]'))hideTip();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')hideTip();if($('#menu').open||e.target.closest('input,select,textarea'))return;if(['ArrowRight','ArrowDown','PageDown'].includes(e.key)){e.preventDefault();step(1);}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();step(-1);}});
let wheel=0;stage.addEventListener('wheel',e=>{if(e.ctrlKey)return;if(e.deltaY>0&&stage.scrollTop+stage.clientHeight<stage.scrollHeight-3)return;if(e.deltaY<0&&stage.scrollTop>3)return;e.preventDefault();if(Date.now()-wheel<500)return;wheel=Date.now();step(e.deltaY>0?1:-1);},{passive:false});
let gesture=null,suppressUntil=0;const scrolls=(node,dy)=>{for(let el=node;el&&el.nodeType===1;el=el.parentElement){if(/auto|scroll/.test(getComputedStyle(el).overflowY)&&el.scrollHeight>el.clientHeight+3){if(dy<0&&el.scrollTop+el.clientHeight<el.scrollHeight-3)return true;if(dy>0&&el.scrollTop>3)return true;}}return false;};
stage.addEventListener('touchstart',e=>{gesture=null;if(e.touches.length!==1||e.target.closest('input,select,textarea'))return;const t=e.touches[0];gesture={x:t.clientX,y:t.clientY,target:e.target,scroll:false};},{capture:true,passive:true});
stage.addEventListener('touchmove',e=>{if(!gesture||e.touches.length!==1){gesture=null;return;}const t=e.touches[0],dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;if(Math.max(Math.abs(dx),Math.abs(dy))<10)return;if(Math.abs(dx)<=Math.abs(dy)*1.15&&scrolls(gesture.target,dy)){gesture.scroll=true;return;}if(!gesture.scroll&&e.cancelable)e.preventDefault();},{capture:true,passive:false});
stage.addEventListener('touchend',e=>{if(!gesture)return;const g=gesture;gesture=null;const t=e.changedTouches[0],dx=t.clientX-g.x,dy=t.clientY-g.y;if(g.scroll||Math.max(Math.abs(dx),Math.abs(dy))<45)return;const horizontal=Math.abs(dx)>Math.abs(dy)*1.15;if(!horizontal&&(Math.abs(dy)<=Math.abs(dx)*1.15||scrolls(g.target,dy)))return;e.preventDefault();e.stopImmediatePropagation();suppressUntil=Date.now()+450;step((horizontal?dx:dy)<0?1:-1);},{capture:true,passive:false});
stage.addEventListener('touchcancel',()=>gesture=null,{passive:true});stage.addEventListener('click',e=>{if(Date.now()<suppressUntil){e.preventDefault();e.stopImmediatePropagation();}},{capture:true});
window.unitReader={go,chooseText,setMode:(m)=>{mode=m==='sentences'?'sentences':'parts';pos=0;render();},play,stop,get state(){return {textIndex,mode,pos,count:count(),ids:ids(),speed};},get clip(){return clip;},data:D};render();
})();
