from pathlib import Path
from html import escape
import json
R=Path(__file__).resolve().parents[2];U=R/'grade7/unit-1';D=json.loads((U/'reading/content.json').read_text())
css='''@font-face{font-family:Heebo;src:url(../the-same-way/assets/Heebo.ttf)}@font-face{font-family:Nunito;src:url(../the-same-way/assets/Nunito.ttf)}*{box-sizing:border-box}body{margin:0;background:radial-gradient(ellipse at 85% 0,#194a6555,transparent 55%),#071526;color:#f5fbff;font-family:Heebo,Arial,sans-serif}main{max-width:1100px;margin:auto;padding:25px 22px 70px}a{color:#6ce7ff}button,.btn{font:700 16px Heebo;padding:10px 16px;border:1px solid #4d8097;background:#143149;border-radius:10px;color:#f4fbff;text-decoration:none;display:inline-block;cursor:pointer}a:focus-visible,button:focus-visible{outline:3px solid #ffce69;outline-offset:4px}.home{font-size:25px;text-decoration:none}header{margin:30px 0}.eyebrow{color:#63e7ff;font:800 15px Nunito}h1{font:900 clamp(42px,8vw,78px) Nunito;margin:8px 0;color:#dcff72}h2{font-size:26px;margin:0 0 10px}p{font-size:18px;line-height:1.65}.meta{font-size:13px;color:#bad0df}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{padding:25px;border:1px solid #365c73;border-radius:18px;background:#10283b}.card .num{font:900 17px Nunito;color:#77e8ff}.links{display:flex;flex-wrap:wrap;gap:10px;margin-top:18px}.wide{grid-column:1/-1}.route{width:100%;max-width:550px;height:90px;display:block;margin:15px 0;color:#6ce7ff}.teacher{border-color:#ac91ff}.status{font-size:14px;color:#f5d891}.copyStatus{font-size:14px;min-height:24px}.group{margin:12px 0}.group a{margin-left:12px}bdi{font-family:Nunito;direction:ltr}.footnote{font-size:15px;color:#c3d7e5}.teacherMain{max-width:1050px}body.deck{height:100dvh;display:grid;grid-template-rows:55px minmax(0,1fr) 65px;overflow:hidden}.deck header{margin:0;padding:10px 20px;display:flex;gap:20px;align-items:center}.deck main{height:100%;overflow:auto;width:100%;padding:25px}.deck article{max-width:920px;margin:auto;min-height:100%;display:flex;flex-direction:column;justify-content:center}.deck h1{font:900 clamp(30px,4vw,50px) Heebo}.deck p,.deck li{font-size:clamp(20px,2.2vw,28px);line-height:1.65}.deck footer{display:flex;align-items:center;justify-content:center;gap:25px;direction:ltr;background:#10283b}.deck ul{padding-right:25px}.deck .created{font-size:14px}.english{font-family:Nunito;direction:ltr;text-align:left;white-space:pre-line}.evidence{color:#dfff75}.deck #count{font-family:Nunito}.mini{font-size:16px!important}@media(max-width:650px){.grid{grid-template-columns:1fr}.card{padding:20px}.deck main{padding:18px}.deck p,.deck li{font-size:20px}.route{height:65px}.deck header{font-size:13px}.deck h1{font-size:30px}}'''
(U/'unit.css').write_text(css)
svg='''<svg class="route" viewBox="0 0 560 90" role="img" aria-label="דרך לבית הספר: הליכה, אוטובוס ורכבת"><g fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><path stroke-dasharray="5 8" d="M65 55H490"/><circle cx="40" cy="17" r="7"/><path d="M40 25l-5 24-13 22m13-22 18 22M38 32l-15 11m15-11 17 12"/><rect x="200" y="20" width="90" height="43" rx="8"/><path d="M213 30h44v15h-44zM267 30h13v25h-13z"/><circle cx="219" cy="65" r="8"/><circle cx="271" cy="65" r="8"/><rect x="443" y="10" width="57" height="57" rx="12"/><path d="M453 20h36v21h-36zM451 77l8-10m33 10-8-10"/><circle cx="456" cy="53" r="3"/><circle cx="487" cy="53" r="3"/></g></svg>'''
head=lambda title:f'<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} | Teachers</title><link rel="stylesheet" href="unit.css?v=unit1-1"></head>'
html=head('Unit 1 · The Same Way')+'''<body><main><a class="home" href="../">⌂ כיתה ז׳</a><header><span class="eyebrow">לומדים וכותבים ז׳ · יחידה 1</span><h1 dir="ltr">Unit 1</h1><h2 dir="ltr">The Same Way</h2><p>הדרך לבית הספר · קריאה, דקדוק וכתיבה</p><p class="meta">נוצר: יום שני, י׳ בתשרי תשפ״ז (21.9.2026)</p>'''+svg+'''<div class="links"><a class="btn" href="teacher.html">מצגת מדריך למורה ←</a><a class="btn" href="#print">דפים להדפסה ↓</a></div></header><div class="grid">
<section class="card"><span class="num">01 / WORDS</span><h2>אוצר מילים</h2><p>קבוצות 01–02: מילים, משפטים ותרגום מדורג. מתחילים מהמילים הנחוצות לשיעור; אין הנחה שכל הקבוצה כבר נלמדה.</p><div class="links"><a class="btn" href="../band2-groups-01-02/full.html?v=20260916-full2">מצגת אוצר המילים</a></div>'''
for g in ['01','02']:html+=f'<div class="group"><a href="https://englishfornoar.co.il/band-ii/groups/group-{g}.html" target="_blank" rel="noopener">פתיחת קבוצה {g} ↗</a><button data-copy="https://englishfornoar.co.il/band-ii/groups/group-{g}.html">העתקת קישור</button><div class="copyStatus" role="status"></div></div>'
html+='''</section><section class="card"><span class="num">02 / STORY</span><h2>The Same Way</h2><p>ילד בוחר בית ספר רחוק ומגלה שהילדים שפגש בדרך הם חבריו לכיתה. קריאה עם הקראה, פירושי מילים ושאלות.</p><div class="links"><a class="btn" href="../the-same-way/">מצגת הסיפור</a><a class="btn" href="../follow-along/">קריאה מלווה</a><a href="../the-same-way/files/the-same-way-worksheet.pdf">סיפור ומשימות · PDF</a></div></section>
<section class="card"><span class="num">03 / GRAMMAR</span><h2>יש במקום · יש למישהו</h2><p><bdi>There is / There are</bdi> לעומת <bdi>have / has</bdi>. Part A — הווה; Part B — עבר ותרגול משולב. לכל חלק דף מלווה ועצירות כתיבה.</p><div class="links"><a class="btn" href="../there-is-there-are/?v=worksheets-5">מצגת הדקדוק · A + B</a><a href="../../to-be/">חזרה על To Be</a></div></section>
<section class="card"><span class="num">04 / READING WORKSHOP</span><h2>קוראים כדי להבין ולפעול</h2><p>מפגש כפול שבו דף העבודה מוביל: הודעה, קטע מידע, כתיבה ומשימת יישום חדשה. המצגת משמשת למשוב ולהסבר בסוף העבודה.</p><div class="links"><a class="btn" href="reading/">מצגת הבדיקה בכיתה</a><a class="btn" href="reading/?mode=home">חזרה בבית · 10–15 דקות</a></div><p class="status">הטקסטים, התרגומים והתרגול זמינים. ההקראה החדשה בהכנה.</p></section>
<section class="card"><span class="num">05 / REVIEW</span><h2>הכנה למבחן הראשון</h2><p>מילות שאלה ומשפחת How, חזרה על הסיפור וכתיבת משפטים. המבחן המוצע מתמקד בהווה.</p><div class="links"><a class="btn" href="../first-exam-preparation/?v=exam-1">מצגת ההכנה למבחן</a></div></section>
<section class="card teacher"><span class="num">06 / TEACHER</span><h2>מדריך למורה</h2><p>מצגת נפרדת עם סדר ההוראה, תכנון המפגשים, תמיכה בתלמידים, מפתחות ומסמכי ההערכה.</p><div class="links"><a class="btn" href="teacher.html">פתיחת מצגת המדריך</a></div></section>
<section class="card wide" id="print"><h2>דפים להדפסה</h2><p>דפי הדקדוק: עמוד אחד לכל חלק. סדנת הקריאה: שני עמודים, מתאימים להדפסה דו־צדדית.</p><div class="links"><a class="btn" href="../there-is-there-are/files/part-a-companion.pdf">דקדוק Part A · PDF</a><a class="btn" href="../there-is-there-are/files/part-b-companion.pdf">דקדוק Part B · PDF</a><a class="btn" href="files/reading-workshop.pdf">סדנת קריאה · PDF</a><a class="btn" href="../the-same-way/files/the-same-way-worksheet.pdf">הסיפור ומשימות · PDF</a></div></section>
</div><p class="footnote">המצגות המקוריות נשארות זמינות בקישוריהן. תאריכי היצירה שלהן נשמרו.</p></main><script src="hub.js?v=unit1-1"></script></body></html>'''
(U/'index.html').write_text(html)
(U/'hub.js').write_text('''document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{const status=b.parentElement.querySelector('.copyStatus');try{await navigator.clipboard.writeText(b.dataset.copy);status.textContent='הקישור הועתק';}catch(e){status.textContent='העתקה אוטומטית חסומה. בחרו והעתיקו את הקישור: ';const f=document.createElement('input');f.readOnly=true;f.value=b.dataset.copy;f.dir='ltr';f.style.width='100%';status.append(f);f.focus();f.select();}});''')
T=[]
def t(title,body):T.append(dict(title=title,body=body))
t('Unit 1 · מדריך למורה','<p>כיתה ז׳ · The Same Way</p><p>סיפור, אוצר מילים, דקדוק, קריאה שימושית וכתיבה.</p><p class="created">נוצר: יום שני, י׳ בתשרי תשפ״ז (21.9.2026)</p><p class="mini">השתמשו בחצים, בסווייפ או בתפריט השקפים. מדריך זה אינו מצגת התלמידים.</p>')
t('מפת היחידה','<ol><li>מילים נחוצות והסיפור The Same Way.</li><li>דקדוק Part A במפגש כפול; אוספים וסורקים את הדף.</li><li>Part B במפגש נפרד, בהתאמה לממצאים.</li><li>סדנת קריאה עם דף דו־צדדי וחזרה בבית.</li><li>הכנה למבחן והערכה.</li></ol><p class="mini">סדר מוצע, לא מכסת שעות רשמית. מעריכים מחדש לפי העבודה בכיתה.</p>')
t('מטרות שאפשר לראות בעבודה','<ul><li>לזהות למי הודעה מיועדת, מתי ואיפה לפעול.</li><li>להבחין בין נושא מרכזי לפרט ולהביא ראיה.</li><li>לזהות סיבה ואת המידע שכינוי גוף מחליף.</li><li>לכתוב הודעה קצרה ולהבחין בין יש במקום לשייכות.</li></ul>')
t('תמיכה בלי למסור תשובה','<p>הוראות בעברית ופירושי מילים זמינים. מקריאים הוראה ומסבירים מילים לפי הצורך; במשימה עצמאית לא מסמנים אפשרות נכונה.</p><p>בשאלות הבנה מקבלים תשובה קצרה ואף עברית כשאין דרישה אחרת. מפרידים בין קושי בדקדוק, קושי בקריאה וקושי באיות.</p>')
t('שני סוגי דפים, שתי דרכי עבודה','<p><b>דפי הדקדוק:</b> השאלות במשימות 2–4 מופיעות רק בשקפים. משאירים תשובות מוקדמות; אוספים לפני הפתרונות.</p><p><b>דף סדנת הקריאה:</b> הטקסטים ומשימות 1–8 בדף. לאחר ניסיון עצמי מותר להוסיף תיקון בשורה נפרדת. משימות יציאה 9–10 נחשפות בסיום ונאספות לפני הפתרון.</p>')
t('הסיפור · רצף של 72 דקות','<p>4 דק׳ פתיחה; 5 דק׳ קריאה כללית; 7 דק׳ תמיכת מילים; 13 דק׳ פסקאות A–B ומסלול; 10 דק׳ הדאגה לגשם; 14 דק׳ המפגש בכיתה; 3 דק׳ שיחה בזוגות; 8 דק׳ עבודה בדף; 5 דק׳ בדיקה; 3 דק׳ יציאה.</p><p>עוד 8 דקות מרווח. בוחרים קריאה מלווה או משפטים לפי הצורך, בלי להעמיס שני סבבים מלאים.</p>')
t('מפתח דף הסיפור · 1–3','<p>1. הוא אוהב את שיעורי המדעים בבית הספר.</p><p>2. הליכה לתחנה ← אוטובוס ראשון ← רכבת ← אוטובוס שני ← הליכה לבית הספר.</p><p>3. False. ההפתעה בכיתה מלמדת שלא ידע שהילדים ילמדו איתו. ראיה חזקה: The boys from the journey are in my class.</p>')
t('מפתח דף הסיפור · 4–6','<p>4. הוא חושש מהגשם ומהדרך בחורף.</p><p>5. is; are.</p><p>6. יש לו חברים והוא יכול לנסוע איתם. בעיית הגשם עצמה לא נפתרה.</p><p>מקבלים ניסוחים חלופיים נכונים. דמויות הסיפור המקורי נשארות בשמותיהן.</p>')
t('הכנה למבחן · שני שיעורים','<p>שיעור ראשון: 4 דק׳ פתיחה, 10 מילות שאלה, 20 משפחת How, 6 קריאה וחזרה.</p><p>שיעור שני: 14 דק׳ חזרה על הסיפור, 12 יש ושייכות, 10 כתיבה ובדיקה, 4 יציאה. בכל שיעור 5 דקות מרווח.</p><p class="mini">How many לספירה; much לכמות או מחיר; long למשך/אורך; far למרחק; good לאיכות; small לגודל קטן; old לגיל. How big הוא ניסוח כללי לשאלת גודל.</p>')
t('Part A · מפגש כפול','<p>5 דק׳ פתיחה ומשימה 1; 14 דק׳ שייכות ומקום; 13 דק׳ יחיד ורבים ומשימה 2; 14 דק׳ שלילה; 15 דק׳ שאלות ומשימה 3; 5 דק׳ סיכום ומשימה 4; 6 דק׳ איסוף ובדיקה.</p><p>72 דקות מתוכננות + 8 דקות מרווח. אין חובה לשמוע כל זוג משפטים פעמיים.</p>')
t('Part B · מתאים את עצמו לכיתה','<p>הדף והמצגת הם בסיס זמני. אחרי סריקת A בודקים: שייכות או מקום? יחיד או רבים? סדר מילים בשאלה?</p><p>לפי הממצאים מוסיפים חזרה ממוקדת לפני was/were. שומרים מקום לקריאה ולכתיבה, ולא רק להסבר.</p>')
t('סדנת הקריאה · לפני השיעור','<p>מדפיסים <a href="files/reading-workshop.pdf">דף דו־צדדי אחד לתלמיד</a>. חלק א׳ — הודעה; חלק ב׳ — מידע. הגרפיקה מסמנת את סוג הטקסט ואינה מחליפה מידע מילולי.</p><p>התלמידים כותבים תחילה לבד. המצגת נשארת סגורה בזמן העבודה; פותחים את שקפי הבדיקה בסוף.</p>')
t('סדנת הקריאה · 80 דקות','<ul><li>0–5: פתיחה והוראות.</li><li>5–20: הודעה, משימות 1–3.</li><li>20–25: השוואת ראיות בזוגות ובדיקה קצרה בעל פה.</li><li>25–45: קטע מידע, משימות 5–8.</li><li>45–55: כתיבת הודעה — משימה 4.</li><li>55–65: מצגת משוב; 65–70: משימות 9–10 עצמאיות.</li><li>70–72: איסוף וסגירה; 8 דקות נוספות למעברים.</li></ul>')
t('שאלות שעוזרות במקום רמז לתשובה','<ul><li>איפה בטקסט מצאת את המידע?</li><li>מה השאלה מבקשת: אדם, שעה, מקום או סיבה?</li><li>האם הפרט הזה מתייחס לתיק או למטרייה?</li><li>על מי דיבר המשפט שלפני They?</li></ul><p>אם קושי משותף חוזר, עוצרים להסבר קצר בזמן העבודה.</p>')
for q in D['questions']+D['exitQuestions']:
 t('מפתח סדנה · שאלה '+q['id'],f'<p>{escape(q["q"])}</p><p><b>תשובה:</b> {escape(q["opts"][q["correct"]])}</p><p class="english evidence">{escape(q["evidence"])}</p><p>{escape(q["why"])}</p>')
t('משימה 4 · מה מקבלים?','<p>מקבלים חדר ושעה סבירים, תיאור תכולה והוראה ברורה. אין תשובה יחידה.</p><p class="english">Room 5 is open from 7:30.\nThere are chairs in the room.\nPlease put your bags under the tables.</p><p>משוב: קודם האם ההודעה מובנת, אחר כך תיקון ממוקד אחד.</p>')
t('מפתח דקדוק · Part A','<p>1: has / are.</p><p>2: is / are / has.</p><p class="english">3.1 There isn’t a book on the table.\n3.2 Is there a chair in the room?</p><p>4: has / are / Is there.</p>')
t('מפתח דקדוק · Part B','<p>1: is / has.</p><p>2: was / were.</p><p class="english">3.1 There weren’t any books in the drawer.\n3.2 Was there a ball in the drawer?</p><p>4: had / were / are.</p>')
t('מה בודקים אחרי האיסוף?','<p>משווים בין ניסיון עצמאי, תיקון והצלחה בפרט חדש. משימות 9–10 אינן מקבלות פתרון לפני האיסוף.</p><p>רושמים דפוסים: זמן ומקום, מציאת סיבה, כינוי גוף, כתיבה. תשובה חסרה אינה הוכחה לאי־הבנה; בודקים גם קצב וקריאות.</p>')
t('חזרה בבית','<p><a href="reading/?mode=home">מסלול חזרה של 10–15 דקות</a>: שני הטקסטים בחלקים, פירושים לכל מילה, שאלות עם בחירה וראיות, והודעה חדשה.</p><p>התשובה נחשפת בשקף נפרד לאחר בחירה או בקשת בדיקה. ניתן לחזור ולנסות שוב בלי חסימת ניווט.</p><p class="mini">ההקראה החדשה בהכנה; ההקראות בחומרים הקיימים פעילות.</p>')
t('המבחן הראשון וחומרי המורה','<p><a href="https://drive.google.com/file/d/1x5l2swCZE-azQmqYocBsCQ3S2WTM-2sD/view" target="_blank" rel="noopener">המבחן המוצע · PDF ב־Drive</a></p><p><a href="https://docs.google.com/document/d/1HG1acO2qYv09D7pu66zmL6zf4hoXo5Mxlrt6YOBOIkw/edit" target="_blank" rel="noopener">המבחן · גרסה לעריכה</a></p><p>עמוד סיפור ועמוד שאלות. 5 שאלות הבנה ובחירת 5 מתוך 7 משפטי כתיבה. המבחן מתמקד בהווה.</p><p class="mini">הדמיון לאורך מבחן השנה הקודמת הוא נקודת ייחוס; לא אומת שזה בדיוק המבחן הראשון דאז.</p>')
t('התאמה לתוכנית ושחזור','<p>היחידה משלבת הודעה, מידע וסיפור; הבנת פרטים ורעיון מרכזי; כתיבה קצרה. השיוך והקצב הם תכנון הוראה מקומי.</p><p><a href="https://pop.education.gov.il/tchumey_daat/english/chativat-beynayim/curriculum/basic-user-a2/">יעדי A2 — משרד החינוך</a></p><p class="mini">מקור משותף לטקסטים ולמשימות: reading/content.json. פירושי מילים נוספים הם תמיכה לשיעור ואינם טענה שנלמדה כל קבוצה 01–02.</p>')
js='''const S=TEACHER;let i=Math.max(0,Math.min(S.length-1,(parseInt(location.hash.slice(1))||1)-1));const main=document.querySelector('main');function go(n){i=Math.max(0,Math.min(S.length-1,n));main.innerHTML='<article><p class="eyebrow">Unit 1 · מדריך למורה</p><h1>'+S[i].title+'</h1>'+S[i].body+'</article>';main.scrollTop=0;document.querySelector('#count').textContent=(i+1)+' / '+S.length;document.querySelector('#back').disabled=i===0;document.querySelector('#next').disabled=i===S.length-1;document.querySelector('#jump').value=i;history.replaceState(null,'','#'+(i+1));}document.querySelector('#jump').innerHTML=S.map((s,n)=>'<option value="'+n+'">'+(n+1)+'. '+s.title+'</option>').join('');document.querySelector('#jump').onchange=e=>go(Number(e.target.value));document.querySelector('#back').onclick=()=>go(i-1);document.querySelector('#next').onclick=()=>go(i+1);document.addEventListener('keydown',e=>{if(e.target.closest('select'))return;if(['ArrowRight','ArrowDown','PageDown'].includes(e.key)){e.preventDefault();go(i+1)}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();go(i-1)}});let wheel=0;main.addEventListener('wheel',e=>{if(e.deltaY>0&&main.scrollTop+main.clientHeight<main.scrollHeight-3)return;if(e.deltaY<0&&main.scrollTop>3)return;e.preventDefault();if(Date.now()-wheel<500)return;wheel=Date.now();go(i+(e.deltaY>0?1:-1))},{passive:false});'''
engine=(R/'grade7/there-is-there-are/lesson.js').read_text();swipe=engine[engine.index('function installSwipe'):engine.index("installSwipe($('#stage')")];js+=swipe+"installSwipe(main,d=>go(i+d));go(i);window.teacher={go,slides:S};"
(U/'teacher-data.js').write_text('const TEACHER='+json.dumps(T,ensure_ascii=False)+';\n');(U/'teacher.js').write_text(js)
(U/'teacher.html').write_text(head('Unit 1 · מדריך למורה')+'<body class="deck"><header><a class="home" href="../" aria-label="כיתה ז׳">⌂</a><a href="./">Unit 1</a><select id="jump" aria-label="בחירת שקף" style="max-width:60%;font:inherit"></select></header><main tabindex="-1"></main><footer><button id="back" aria-label="השקף הקודם">←</button><span id="count"></span><button id="next" aria-label="השקף הבא">→</button></footer><script src="teacher-data.js?v=unit1-1"></script><script src="teacher.js?v=unit1-1"></script></body></html>')
# Group the existing unit materials under one entry, preserving their direct URLs.
p=R/'grade7/index.html';s=p.read_text();a=s.index('<a class="card"');b=s.index('<a class="card secondary"',a)
s=s[:a]+'''<a class="card" href="unit-1/"><span class="tag">יחידת לימוד · סיפור, קריאה, דקדוק וכתיבה</span><h2 lang="en" dir="ltr">Unit 1 · The Same Way</h2><p>כל חומרי היחידה במקום אחד: קבוצות 01–02, הסיפור, There is / There are, דפי ליווי, סדנת קריאה, חזרה לבית והכנה למבחן. מצגת מדריך למורה בקישור נפרד.</p><p style="font-size:14px">נוצר: יום שני, י׳ בתשרי תשפ״ז (21.9.2026)</p><span class="open">פתיחת היחידה ←</span></a>'''+s[b:];p.write_text(s)
print('Hub and',len(T),'teacher slides')
