"""Remaining preparation meetings before the approved 22 October first exam."""
MEETINGS = [
 dict(date='2026-10-08',title='The journey and the choice',count=28,
 skills=['Read for the main idea','Put events in order','Distinguish possession from location'],
 goal='Explain why the boy chose the school and map his journey.',
 reading=[('The Same Way · story and questions','../the-same-way/'),('Story worksheet · questions 1–2','../the-same-way/files/the-same-way-worksheet.pdf')],
 reading_task='Read the whole story once for meaning. Revisit the opening and journey. Find the reason for choosing this school and put the five travel stages in order. Use selected sentence slides only where help is needed.',
 grammar=('Part A · possession and location, slides 4–36','../there-is-there-are/#4'),
 grammar_task='Use slides 5, 10 and 21, then one example per rule. Complete Part A tasks 1–2. Keep early answers for comparison. Remaining examples are home practice.',
 writing=[('Story worksheet · questions 1–2','../the-same-way/files/the-same-way-worksheet.pdf'),('Part A companion sheet','../there-is-there-are/files/part-a-companion.pdf')],
 writing_task='Write two sentences about the journey and one about what the boy has. In the final four minutes, explain the difference between He has and There is.',
 prep=['Bring the story worksheet, Part A sheet and notebook.','Think about how you get to school.'],
 home=[('Reread the journey with audio. Retell the route in order.','../follow-along/'),('Review Part A slides 4–36 and correct one sentence without erasing your first attempt.','../there-is-there-are/#4'),('Finish story questions 1–2 and write one new There is sentence.','../the-same-way/files/the-same-way-worksheet.pdf')],
 check='Accept a correct route and a text-based reason. Check possession and location separately.',support='Let pupils point to evidence and say their answer before writing.',exit='Explain the school choice using a detail from the story.'),
 dict(date='2026-10-11',title='Rain, friends and questions',count=27,
 skills=['Infer feelings from evidence','Explain a change in the story','Form present-tense negatives and questions'],
 goal='Explain what changes when the boy meets his classmates and what remains uncertain.',
 reading=[('The Same Way · rain and classroom ending','../the-same-way/'),('Story worksheet · questions 3–6','../the-same-way/files/the-same-way-worksheet.pdf')],
 reading_task='Revisit the rain worry and the classroom ending. Find evidence that the boy did not know the other boys were his classmates. Discuss shared feelings. Complete questions 3–6, including the unresolved rain problem.',
 grammar=('Part A · negatives and questions, slides 37–81','../there-is-there-are/#37'),
 grammar_task='Model with slides 37 and 58, then one example each. Use worksheet tasks 3–4 and collect the sheet before showing the answer slides. Revisit errors next meeting.',
 writing=[('Part A companion sheet · tasks 3–4','../there-is-there-are/files/part-a-companion.pdf'),('Story worksheet','../the-same-way/files/the-same-way-worksheet.pdf')],
 writing_task='Write one negative and one question about a room. Answer one story question with evidence. In the final four minutes, explain why finding friends does not solve the rain problem.',
 prep=['Bring your story answers and Part A sheet.','Prepare one detail that shows the boy’s feelings.'],
 home=[('Replay the ending and retell what changes in the classroom.','../follow-along/'),('Review selected negative and question examples in slides 37–80.','../there-is-there-are/#37'),('Finish story questions 3–6 and improve one answer with evidence.','../the-same-way/files/the-same-way-worksheet.pdf')],
 check='Do not accept that he knew they were classmates or that the rain problem is solved.',support='Separate the practical problem from the change in feelings. Rehearse a question aloud.',exit='Write an Is there or Are there question without copying.'),
 dict(date='2026-10-15',title='Reading workshop: a message and information',count=28,
 skills=['Find audience, time and place','Identify the main idea and a reason','Resolve a pronoun reference'],
 goal='Use evidence to answer questions about two short texts.',
 reading=[('Reading workshop · printed tasks 1–3 and 5–8','files/reading-workshop.pdf'),('Feedback slides · open after independent work','reading/')],
 reading_task='Use the printed sheet first: 9 minutes for the message and tasks 1–3, 11 for the information text and tasks 5–8, then 4 for paired evidence checking. Keep feedback slides closed until pupils have tried.',
 grammar=('Part A · targeted repair from collected work','../there-is-there-are/#5'),
 grammar_task='Spend 6 minutes checking the reading with selected feedback slides and 8 repairing one shared grammar difficulty. Use the message to contrast what is in a room with what pupils have.',
 writing=[('Workshop · task 4','files/reading-workshop.pdf')],
 writing_task='Draft a three-sentence message with a room, a time and an instruction. Use the final four minutes to underline the evidence for a reading answer. Keep transfer tasks 9–10 for the next meeting.',
 prep=['Bring the two-sided reading workshop sheet and notebook.','Recall how to find who, when and where in a message.'],
 home=[('Review the message with audio and check your evidence for tasks 1–3.','reading/?mode=home'),('Review the information text and your answers to tasks 5–8. Stop before the new-message transfer task.','reading/?mode=home'),('Improve your task 4 message. Include a clear time, place and instruction.','files/reading-workshop.pdf')],
 check='Check the reason, main idea and They reference separately. A copied detail may not answer the question.',support='Ask where the evidence is. Explain an unfamiliar word without selecting an answer.',exit='Underline the words that justify one answer.'),
 dict(date='2026-10-18',title='Transfer, question words and exam practice',count=27,
 skills=['Apply reading skills to a new message','Choose a question word','Write and check a short message independently'],
 goal='Apply the unit skills independently before the first exam on 22 October.',
 reading=[('Workshop · new-message tasks 9–10','files/reading-workshop.pdf'),('First exam preparation · question words and How','../first-exam-preparation/')],
 reading_task='Allow 6 minutes for tasks 9–10 independently and collect before answers. Use 12 minutes for selected question-word and How examples, then 6 to justify answers with evidence. Sample the deck rather than running every slide.',
 grammar=('Part A · present-tense review','../there-is-there-are/#77'),
 grammar_task='Use the collected work to revisit there is/are and have/has, one negative and one question. Pupils answer first, then check. Past forms in Part B are an extension after this exam.',
 writing=[('Workshop · task 4 revision','files/reading-workshop.pdf'),('First exam preparation','../first-exam-preparation/')],
 writing_task='Write a new three-sentence school message without a model. Check meaning first, then one grammar point. Use the last four minutes to name one skill to practise before the exam.',
 prep=['Bring both worksheets and your revised message.','Choose one question you still have about the unit.'],
 home=[('Review the story and retell the choice, worry and ending.','../follow-along/'),('Practise selected question-word and How questions.','../first-exam-preparation/'),('Review the workshop and write a fresh short message, then check it.','reading/?mode=home')],
 check='Use the new-message answers to check transfer. Judge meaning before spelling.',support='Give a brief planning prompt, then let pupils write independently.',exit='Identify one personal review target for 22 October.'),
]
