const mode=document.documentElement.dataset.mode;
const enOnly=mode==="en";
const t=(he,en)=>enOnly?en:he;
const home=document.documentElement.dataset.home || "../";
const slides=[];
const add=(html,note,extra="")=>slides.push({html,note,extra});
const part=(cls,label,text)=>`<span class="chip ${cls}">${label}: <span>${text}</span></span>`;
const sent=(s)=>`<div class="sentence en">${s}</div>`;
const colorSentence=(chunks)=>`<div class="sentence en">${chunks.map(([cls,txt])=>`<span class="${cls}">${txt}</span>`).join(" ")}</div>`;
const note=(he,en)=>enOnly?en:he;

add(`<div class="content"><span class="badge">Grade 11 · 5 Points</span><h1 class="hero en">Advanced Grammar</h1><p class="subtitle">${t("איך משפט באנגלית בנוי — ואיך הופכים אותו למשפט ברמת G","How English sentences work — and how we make them stronger for Module G")}</p></div>`,note("היום אנחנו לא לומדים את כל הדקדוק לעומק. היום אנחנו מבינים מה מצופה מכתיבה ברמת G.","Today we are not mastering every grammar topic. We are understanding what G-level writing is expected to show."));
add(`<div class="content"><div class="eyebrow">Basic Structure</div><h1 class="title">${t("משפט באנגלית בדרך כלל בנוי כך","Most English sentences have a clear structure")}</h1><div class="hero en">S + V + O</div><div class="legend">${part("subject","Subject",t("מי / מה","who / what"))}${part("verb","Verb",t("הפעולה","the action"))}${part("object","Object",t("מקבל הפעולה","receives the action"))}</div></div>`,note("באנגלית יש סדר. קודם מי או מה, אחר כך הפועל, ואז על מה או על מי הפעולה נעשית.","English likes order: who or what, then the verb, then who or what receives the action."));
add(`<div class="content"><div class="eyebrow">Example 1</div><h1 class="title">${t("משפט קצר, אותו מבנה","Short sentence, same structure")}</h1>${colorSentence([["subject","Students"],["verb","learn"],["object","English."]])}<div class="parts">${part("subject","Subject","Students")}${part("verb","Verb","learn")}${part("object","Object","English")}</div></div>`,note("גם משפט קצר מאוד אפשר לפרק לשלושה חלקים. זה הבסיס שעליו אנחנו בונים.","Even a very short sentence can be broken into three parts. This is the base we build on."));
add(`<div class="content"><div class="eyebrow">Example 2</div><h1 class="title">${t("משפט פעולה","Action sentence")}</h1>${colorSentence([["subject","Technology"],["verb","helps"],["object","students."]])}<div class="parts">${part("subject","Subject","Technology")}${part("verb","Verb","helps")}${part("object","Object","students")}</div></div>`,note("מי עושה? Technology. מה עושה? helps. את מי? students.","Who acts? Technology. What does it do? helps. Who receives the action? students."));
add(`<div class="content"><div class="eyebrow">Example 3</div><h1 class="title">${t("לא כל משפט הוא פעולה","Not every sentence has an action")}</h1>${colorSentence([["subject","The text"],["verb","is"],["desc","difficult."]])}<div class="parts">${part("subject","Subject","The text")}${part("verb","Verb","is")}${part("desc","Description","difficult")}</div><p class="subtitle">${t("עם to be אנחנו מתארים את הנושא.","With to be, we often describe the subject.")}</p></div>`,note("כאן אין פעולה חזקה. הטקסט לא עושה משהו. אנחנו מתארים אותו.","There is no strong action here. The text is not doing something. We are describing it."));
add(`<div class="content"><div class="eyebrow">Example 4</div><h1 class="title">${t("to be מתאר מצב","To be describes a situation")}</h1>${colorSentence([["subject","Many students"],["verb","are"],["desc","nervous"],["","before an exam."]])}<div class="parts">${part("subject","Subject","Many students")}${part("verb","Verb","are")}${part("desc","Description","nervous")}${part("","Extra","before an exam")}</div></div>`,note("are מחבר בין התלמידים לבין התיאור שלהם. גם זה משפט מלא.","are connects the students to their description. This is also a complete sentence."));
add(`<div class="content"><div class="eyebrow">Example 5</div><h1 class="title">${t("הנושא יכול להיות ארוך","The subject can be long")}</h1>${colorSentence([["subject","A student who practices every week"],["verb","is"],["desc","more confident"],["","in English."]])}<div class="parts">${part("subject","Subject","A student who practices every week")}${part("verb","Verb","is")}${part("desc","Description","more confident")}</div></div>`,note("כל החלק הראשון הוא Subject אחד ארוך. לא להיבהל מאורך.","The whole first part is one long subject. Length is not the problem."));
add(`<div class="content"><div class="eyebrow">Example 6</div><h1 class="title">${t("משפט ארוך עדיין יכול להיות פשוט","Long does not always mean advanced")}</h1>${colorSentence([["subject","Responsible students"],["verb","develop"],["object","strong reading habits"],["","during the year."]])}<div class="parts">${part("subject","Subject","Responsible students")}${part("verb","Verb","develop")}${part("object","Object","strong reading habits")}</div><p class="subtitle">${t("אורך המשפט לא קובע אם הוא מתקדם.","Length alone does not make a sentence advanced.")}</p></div>`,note("אורך זה לא קסם. משפט ארוך יכול עדיין להיות רגיל לגמרי.","Length is not magic. A long sentence can still be completely basic."));
add(`<div class="content"><div class="eyebrow">Transition</div><h1 class="title">${t("אבל באנגלית זה לא תמיד S + V + O","But English is not always S + V + O")}</h1><div class="two"><div class="panel cyan"><h2>${t("משנים סדר","Change order")}</h2><p>${t("לפעמים הפועל זז","Sometimes the verb moves")}</p></div><div class="panel gold"><h2>${t("מוסיפים מבנה","Add structure")}</h2><p>${t("פסוקיות, זמנים וצורות פועל","Clauses, tenses and verb forms")}</p></div></div><p class="subtitle adv">Advanced Grammar Structures</p></div>`,note("עד עכשיו ראינו את השלד. עכשיו אנחנו רואים איך תלמיד ברמת G בונה משפטים חכמים יותר.","So far we have seen the skeleton. Now we see how a G-level student builds smarter sentences."));
add(`<div class="content"><div class="eyebrow">Module G Writing</div><h1 class="title">${t("מה חובה?","What is required?")}</h1><div class="two"><div class="panel cyan"><h2>${t("חובה","Required")}</h2><p>${t("להראות שימוש במבנים מתקדמים","Show advanced language structures")}</p></div><div class="panel gold"><h2>${t("יעד כיתתי","Class target")}</h2><p>${t("לפחות 4 מבנים, כדי ש־3 יהיו חזקים","At least 4, so 3 remain strong")}</p></div></div><p class="subtitle">${t("לא חייבים להשתמש בכל המבנים.","You do not have to use every structure.")}</p></div>`,note("לא נכתוב בדיוק שלושה ונקווה לטוב. נכוון לארבעה, כדי שאם אחד חלש עדיין יש מספיק מבנים טובים.","We will not write exactly three and hope. We aim for four, so if one is weak, we still have enough strong structures."));
add(`<div class="content"><div class="eyebrow">Official List</div><h1 class="title">${t("מבנים מתקדמים מוגדרים","Defined advanced structures")}</h1><div class="list"><span class="chip adv">Passive Voice</span><span class="chip adv">Conditionals</span><span class="chip adv">Inversion</span><span class="chip adv">Gerunds / Infinitives</span><span class="chip adv">Relative Clauses</span><span class="chip adv">Reported Speech</span><span class="chip adv">Indirect Questions</span><span class="chip adv">Perfect Tenses</span><span class="chip adv">Temporal Clauses</span><span class="chip adv">Complex Sentences</span></div></div>`,note("זו הרשימה שנעבוד איתה. לא כל המבנים צריכים להיכנס לכל חיבור, אבל צריך לדעת לבחור מהם.","This is the list we will work with. Not every structure must appear in every essay, but we need to know how to choose."));
add(`<div class="content"><div class="eyebrow">Passive Voice</div><h1 class="title">${t("ה־Object הופך ל־Subject","The Object becomes the Subject")}</h1><div class="move"><div class="panel"><h2>Active</h2>${sent(`<span class="subject">People</span> <span class="verb">use</span> <span class="object">technology</span> in schools.`)}<div class="parts">${part("subject","Subject","People")}${part("verb","Verb","use")}${part("object","Object","technology")}</div></div><div class="arrow">→</div><div class="panel gold"><h2>Passive</h2>${sent(`<span class="subject">Technology</span> <span class="verb">is used</span> in schools.`)}<div class="parts">${part("subject","Subject","Technology")}${part("verb","Verb","is used")}</div></div></div></div>`,note("Passive זה לא קסם. לוקחים את הדבר שקיבל את הפעולה ושמים אותו בתחילת המשפט.","Passive is not magic. We take the thing that received the action and move it to the front."));
add(`<div class="content"><div class="eyebrow">Conditionals</div><h1 class="title">If + result</h1>${sent(`<span class="adv">If students use technology responsibly</span>, they can learn more effectively.`)}<div class="parts">${part("adv","If clause","If students use technology responsibly")}${part("","Result","they can learn more effectively")}</div></div>`,note("זה מבנה מעולה לכתיבה כי הוא מראה קשר בין תנאי לתוצאה.","This is excellent for writing because it shows a connection between condition and result."));
add(`<div class="content"><div class="eyebrow">Inversion</div><h1 class="title">${t("משנים את הסדר הרגיל","Changing the normal order")}</h1>${sent(`<span class="adv">Not only can</span> technology distract students, but it can also support learning.`)}<p class="subtitle">${t("לא: Not only technology can","Not: Not only technology can")}</p></div>`,note("כאן can זז לפני technology. זה סימן ברור למבנה מתקדם.","Here can moves before technology. That is a clear advanced structure."));
add(`<div class="content"><div class="eyebrow">Gerunds</div><h1 class="title">Verb + ing as a noun</h1>${sent(`<span class="adv">Using technology responsibly</span> can improve learning.`)}<div class="parts">${part("adv","Gerund phrase","Using technology responsibly")}${part("verb","Verb","can improve")}${part("object","Object","learning")}</div></div>`,note("Using כאן מתפקד כמו שם עצם: השימוש בטכנולוגיה.","Using works like a noun here: the use of technology."));
add(`<div class="content"><div class="eyebrow">Infinitives</div><h1 class="title">to + verb</h1>${sent(`Students need <span class="adv">to develop</span> strong writing skills.`)}<div class="parts">${part("subject","Subject","Students")}${part("verb","Verb","need")}${part("adv","Infinitive","to develop")}</div></div>`,note("to develop, to improve, to understand — אלה כלים פשוטים וטובים לכתיבה.","to develop, to improve, to understand are simple and useful writing tools."));
add(`<div class="content"><div class="eyebrow">Relative Clauses</div><h1 class="title">${t("מוסיפים מידע בתוך המשפט","Adding information inside the sentence")}</h1>${sent(`Students <span class="adv">who read regularly</span> improve their vocabulary.`)}<div class="parts">${part("subject","Subject","Students who read regularly")}${part("adv","Relative clause","who read regularly")}</div></div>`,note("במקום שני משפטים קצרים, מחברים מידע למשפט אחד בוגר.","Instead of two short sentences, we connect information into one mature sentence."));
add(`<div class="content"><div class="eyebrow">Perfect Tenses</div><h1 class="title">has / have + V3</h1>${sent(`Technology <span class="adv">has changed</span> the way students learn.`)}<div class="parts">${part("subject","Subject","Technology")}${part("adv","Present Perfect","has changed")}</div></div>`,note("Present Perfect מתאים כשמדברים על שינוי שהתחיל בעבר ומשפיע עד היום.","Present Perfect works well for a change that began in the past and still matters now."));
add(`<div class="content"><div class="eyebrow">Reported Speech</div><h1 class="title">${t("מדווחים על טענה","Reporting an idea")}</h1>${sent(`Many teachers <span class="adv">believe that</span> technology can support learning.`)}<div class="parts">${part("adv","Reported idea","believe that technology can support learning")}</div></div>`,note("זה עוזר להציג טענה או דעה בצורה בוגרת.","This helps present an opinion or claim in a mature way."));
add(`<div class="content"><div class="eyebrow">Indirect Questions</div><h1 class="title">${t("שאלה עקיפה","Indirect question")}</h1>${sent(`It is important to understand <span class="adv">why students use technology</span>.`)}<p class="subtitle">${t("לא: why do students use technology","Not: why do students use technology")}</p></div>`,note("בשאלה עקיפה הסדר שונה. אין do כמו בשאלה רגילה.","In an indirect question the order changes. We do not use do like in a direct question."));
add(`<div class="content"><div class="eyebrow">Temporal Clauses</div><h1 class="title">${t("פסוקיות זמן","Time clauses")}</h1>${sent(`<span class="adv">When technology is used responsibly</span>, it can support learning.`)}<div class="parts">${part("adv","Temporal clause","When technology is used responsibly")}${part("verb","Passive","is used")}</div></div>`,note("when, while, before, after, until מחברים זמן ורעיון.","when, while, before, after and until connect time and idea."));
add(`<div class="content"><div class="eyebrow">Complex Sentences</div><h1 class="title">${t("מציגים רעיון מורכב","Showing a complex idea")}</h1>${sent(`<span class="adv">Although</span> technology can distract students, it can also support learning.`)}<div class="parts">${part("adv","Contrast","Although")}</div></div>`,note("Although מאפשר להציג שני צדדים: בעיה מצד אחד ויתרון מצד שני.","Although lets us show two sides: a problem and an advantage."));
add(`<div class="content"><div class="eyebrow">G-Level Sentence</div><h1 class="title">${t("משפט אחד, כמה מבנים","One sentence, several structures")}</h1>${sent(`<span class="adv">Not only can</span> technology distract students, but it can also help them <span class="adv">when it is used responsibly</span>.`)}<div class="parts">${part("adv","Inversion","Not only can")}${part("adv","Temporal clause","when")}${part("adv","Passive","is used")}</div></div>`,note("זה משפט G אמיתי: ברור, לא מסובך מדי, ויש בו כמה מבנים מתקדמים.","This is a real G-level sentence: clear, not too complicated, and rich in advanced structures."));
add(`<div class="content"><div class="eyebrow">How We Count</div><h1 class="title">${t("לא מספיק משפט אחד חכם","One smart sentence is not enough")}</h1><div class="two"><div class="panel gold"><h2>${t("המשפט הזה נספר כ־1","This sentence counts as 1")}</h2><p>${t("גם אם יש בו כמה מבנים","Even if it includes several structures")}</p></div><div class="panel cyan"><h2>${t("צריך לפחות 3 משפטים","We need at least 3 sentences")}</h2><p>${t("שלושה משפטים שונים עם מבנים מתקדמים","Three different sentences with advanced structures")}</p></div></div><p class="subtitle">${t("אפשר לשלב כמה מבנים במשפט אחד, אבל בבחינה אנחנו רוצים להראות מבנים מתקדמים בכמה משפטים.","You may combine several structures in one sentence, but in the exam we want advanced structures to appear in several sentences.")}</p></div>`,note("הנקודה כאן חשובה: משפט אחד עם שלושה מבנים עדיין לא נותן לנו שלושה משפטים מתקדמים. אנחנו רוצים לפחות שלושה משפטים שונים שמראים שליטה.","This point matters: one sentence with three structures still does not give us three advanced sentences. We want at least three different sentences that show control."));

[
  ["טכנולוגיה משמשת בבתי ספר רבים כדי לעזור לתלמידים ללמוד.","Many schools use technology to help students learn.","Passive Voice + Infinitive","Technology is used in many schools to help students learn."],
  ["אם תלמידים מתרגלים קריאה כל שבוע, הם משפרים את אוצר המילים שלהם.","Students practice reading every week. They improve their vocabulary.","Conditional","If students practice reading every week, they improve their vocabulary."],
  ["תלמידים שקוראים טקסטים קשים מפתחים ביטחון באנגלית.","Students read difficult texts. They develop confidence in English.","Relative Clause","Students who read difficult texts develop confidence in English."],
  ["האינטרנט שינה את הדרך שבה תלמידים לומדים.","The internet changed learning, and the effect continues today.","Present Perfect","The internet has changed the way students learn."],
  ["לא רק שטכנולוגיה יכולה להסיח את דעתם של תלמידים, היא גם יכולה לעזור להם כאשר משתמשים בה באחריות.","Technology can distract students. It can also help them when people use it responsibly.","Inversion + Passive","Not only can technology distract students, but it can also help them when it is used responsibly."]
].forEach(([hePrompt,enPrompt,structure,answer],i)=>{
  add(`<div class="content"><div class="eyebrow">Practice ${i+1}</div><h1 class="title">${t("תרגמו לאנגלית","Rewrite using advanced grammar")}</h1><div class="practice-question">${t(hePrompt,enPrompt)}</div><p class="subtitle">${t("נסו להשתמש במבנה מתקדם: ","Try to use: ")}<span class="adv">${structure}</span></p><div class="answer">${answer}</div><div class="parts answer">${part("adv","Advanced structure",structure)}</div></div>`,note("קודם נותנים לתלמידים לנסות. בלחיצה הבאה חושפים את התשובה ומסמנים את המבנה.","First let students try. On the next click, reveal the answer and name the structure."),"practice");
});

add(`<div class="content"><div class="eyebrow">Exam Strategy</div><h1 class="title">${t("עוזרים לבוחן לראות","Help the examiner see it")}</h1><div class="essay"><p><span class="adv">Although</span> technology can distract students, it can also support learning.</p><p>Students <span class="adv">who use it responsibly</span> become more independent.</p><p>In recent years, technology <span class="adv">has changed</span> the way students study.</p></div><div class="mini-list"><span class="chip adv">Although = Complex Sentence</span><span class="chip adv">who use it = Relative Clause</span><span class="chip adv">has changed = Present Perfect</span></div><p class="subtitle">${t("בסוף פסקה אפשר לסמן לעצמכם את המבנים כדי שלא יחמיצו אותם.","At the end of a paragraph, you can mark the structures so they are not missed.")}</p></div>`,note("אני רוצה שהתלמידים יבינו שזה גם עניין של נראות. אם המבנים מוסתרים בתוך כתיבה ארוכה, בוחן עלול לפספס. לכן מתרגלים לזהות ולסמן אותם לעצמנו.","Students should understand that visibility matters too. If structures are hidden inside long writing, an examiner may miss them. So we practice identifying and marking them for ourselves."));

add(`<div class="content"><div class="eyebrow">Final Message</div><h1 class="title">${t("כתיבה היא בחירה חכמה","Writing is smart choice")}</h1><div class="two"><div class="panel cyan"><h2>${t("בחרו מילים שאתם יודעים","Choose words you know")}</h2><p>${t("אל תילחמו במילים זרות","Do not fight unknown words")}</p></div><div class="panel gold"><h2>${t("בחרו מבנים שאתם שולטים בהם","Choose structures you control")}</h2><p>${t("לפחות 4 מבנים מתקדמים","At least 4 advanced structures")}</p></div></div></div>`,note("כתיבה יכולה להיות קלה יותר כי אתם בוחרים במה להשתמש. המטרה היא לא להסתבך, אלא לכתוב ברור, נכון ובוגר.","Writing can be easier because you choose what to use. The goal is not complication; it is clear, accurate and mature writing."));

document.querySelector(".home").href=home;
const deck=document.getElementById("deck");
slides.forEach(s=>{const el=document.createElement("section");el.className=`slide ${s.extra||""}`;el.innerHTML=`${s.html}<div class="teacher-note">${s.note}</div>`;deck.appendChild(el)});
let index=0,wheelLock=false,touchX=0,touchY=0,revealed=false;
const all=[...document.querySelectorAll(".slide")],counter=document.getElementById("counter"),progress=document.getElementById("progress"),prev=document.getElementById("prev"),next=document.getElementById("next");
function show(n){index=Math.max(0,Math.min(all.length-1,n));revealed=false;all.forEach((s,i)=>{s.classList.toggle("active",i===index);s.classList.remove("reveal")});counter.textContent=`${index+1} / ${all.length}`;progress.style.width=`${(index+1)/all.length*100}%`;prev.disabled=index===0;next.disabled=index===all.length-1;location.hash=`slide-${index+1}`}
function forward(){if(all[index].classList.contains("practice")&&!revealed){all[index].classList.add("reveal");revealed=true;return}show(index+1)}
function back(){show(index-1)}
prev.onclick=back;next.onclick=forward;
document.addEventListener("keydown",e=>{if(["ArrowRight","ArrowDown","PageDown"," ","Enter"].includes(e.key)){e.preventDefault();forward()}if(["ArrowLeft","ArrowUp","PageUp"].includes(e.key)){e.preventDefault();back()}if(e.key==="Home")show(0);if(e.key==="End")show(all.length-1)});
document.addEventListener("wheel",e=>{if(wheelLock||Math.abs(e.deltaY)<18)return;wheelLock=true;e.deltaY>0?forward():back();setTimeout(()=>wheelLock=false,430)},{passive:true});
document.addEventListener("touchstart",e=>{touchX=e.touches[0].clientX;touchY=e.touches[0].clientY},{passive:true});
document.addEventListener("touchend",e=>{const dx=touchX-e.changedTouches[0].clientX,dy=touchY-e.changedTouches[0].clientY,d=Math.abs(dy)>Math.abs(dx)?dy:dx;if(Math.abs(d)>45)d>0?forward():back()},{passive:true});
const hash=Number((location.hash.match(/slide-(\d+)/)||[])[1]);show(hash?hash-1:0);
