(()=>{'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rateKey='teachers-read-alone-speed-v1',stateKey='teachers-g9-u1-readalone-v1',rates=[1,.75,.5,.35,.25];
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch(e){return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
let saved=read(stateKey,{});if(!saved||typeof saved!=='object')saved={};let speed=Number(read(rateKey,.75));if(!rates.includes(speed))speed=.75;
let data=null,mode=new URLSearchParams(location.search).get('mode')==='sentences'?'sentences':'text',index=0,started=false,run=0,timer=0,frame=0,range=null,pageRange=null,lastSentence=0,activeWord='',pinned=null;
const audio=$('#audio');audio.playbackRate=speed;audio.preservesPitch=true;$('#speed').value=String(speed);const owner=Math.random().toString(36).slice(2);let channel;try{channel=new BroadcastChannel('teachers-read-alone-audio-v1');channel.onmessage=e=>{if(e.data!==owner)pause()}}catch(e){}
function status(s){$('#status').textContent=s}
function persist(){saved[mode]=index;write(stateKey,saved)}
function count(){return mode==='text'?data.pages.length:data.sentences.length*2}
function ids(){return mode==='text'?data.pages[index].ids:[Math.floor(index/2)]}
function clearWord(){document.querySelectorAll('.spoken,.currentSentence').forEach(e=>e.classList.remove('spoken','currentSentence'));activeWord=''}
function pause(){run++;clearTimeout(timer);cancelAnimationFrame(frame);audio.pause();clearWord();$('#play').textContent='▶ הקראה';$('#play').setAttribute('aria-pressed','false')}
function sync(){if(!data||!range)return;let id='';for(const n of ids()){const s=data.sentences[n];const j=s.words.findIndex(w=>audio.currentTime>=w.start&&audio.currentTime<w.end);if(j>=0){id=n+'-'+j;lastSentence=n;break}}if(id!==activeWord){clearWord();activeWord=id;if(id){const node=document.querySelector('[data-word="'+id+'"]');node?.classList.add('spoken');node?.closest('.sentence')?.classList.add('currentSentence')}}$('#seek').value=String(Math.max(0,Math.min(1000,1000*(audio.currentTime-pageRange.start)/(pageRange.end-pageRange.start))));$('#elapsed').textContent=Math.max(0,audio.currentTime-pageRange.start).toFixed(0)+' / '+(pageRange.end-pageRange.start).toFixed(0)+' שנ׳';}
function finish(){const wasPage=range?.kind==='page';pause();if(wasPage){if(mode==='text'){const done=new Set(Array.isArray(saved.completed)?saved.completed:[]);done.add(index);saved.completed=[...done];persist();$('#tabs [aria-selected="true"]')?.classList.add('done')}$('#next').classList.add('ready');status('הקטע הסתיים. לחצו על המשך כשאתם מוכנים.')}else status('המשפט הסתיים. אפשר לחזור עליו או להמשיך.');$('#seek').value=String(Math.min(1000,1000*(audio.currentTime-pageRange.start)/(pageRange.end-pageRange.start)))}
async function play(restart=false,custom=null){if(!data)return;pause();started=true;range=custom||{...pageRange,kind:'page'};const serial=run;const seek=restart||audio.currentTime<range.start||audio.currentTime>=range.end-.02;if(seek)audio.currentTime=Math.max(0,range.start-.025);audio.playbackRate=speed;audio.preservesPitch=true;channel?.postMessage(owner);try{localStorage.setItem('teachers-read-alone-audio-owner-v1',owner)}catch(e){}try{await audio.play();if(serial!==run||document.hidden){audio.pause();return}$('#play').textContent='❚❚ השהיה';$('#play').setAttribute('aria-pressed','true');status(mode==='text'?'בסיום החלק ההקראה נעצרת.':'המשפט מוקרא ברצף; כל מילה מודגשת בזמן אמירתה.');function tick(){if(serial!==run)return;sync();if(audio.currentTime>=range.end+.015){finish();return}frame=requestAnimationFrame(tick)}tick()}catch(e){if(serial===run)status(e.name==='NotAllowedError'?'כדי להתחיל בנייד, לחצו על ▶ הקראה.':'לא ניתן להשמיע כעת. בדקו את החיבור ולחצו שוב על הקראה.');$('#play').textContent='▶ הקראה'}}
audio.addEventListener('timeupdate',()=>{if(!audio.paused){sync();if(range&&audio.currentTime>=range.end+.015)finish()}});audio.addEventListener('ended',finish);audio.addEventListener('error',()=>status('קובץ ההקראה לא נטען. הטקסט והתרגומים זמינים; נסו לרענן.'));
function hideMeaning(){pinned=null;document.querySelectorAll('.looked').forEach(n=>n.classList.remove('looked'));$('#meaning').textContent='נגיעה במילה או בביטוי מציגה פירוש כאן.'}
function meaning(el,pin=false){if(!el)return;if(pin&&pinned===el){hideMeaning();return}document.querySelectorAll('.looked').forEach(n=>n.classList.remove('looked'));el.classList.add('looked');$('#meaning').textContent=el.dataset.he;el.setAttribute('aria-describedby','meaning');if(pin)pinned=el}
function target(e){return e.target.closest(mode==='text'?'.phrase':'.word')}
$('#panel').addEventListener('pointerover',e=>{if(e.pointerType!=='touch'&&!pinned)meaning(target(e))});$('#panel').addEventListener('focusin',e=>meaning(target(e)));$('#panel').addEventListener('click',e=>{const t=target(e);if(t)meaning(t,true)});$('#panel').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&target(e)){e.preventDefault();e.stopPropagation();meaning(target(e),true)}});
function words(s,n,a=0,b=s.words.length){let output='',pos=a===0?0:s.words[a].charStart;for(let j=a;j<b;j++){const w=s.words[j];output+=esc(s.en.slice(pos,w.charStart));output+='<span class="word" data-word="'+n+'-'+j+'" data-he="'+esc(w.he)+'"'+(mode==='sentences'?' role="button" tabindex="0" aria-label="'+esc(w.text)+' — פירוש"':'')+'>'+esc(w.text)+'</span>';pos=w.charEnd}const end=b===s.words.length?s.en.length:s.words[b].charStart;output+=esc(s.en.slice(pos,end));return output}
function sentence(n){const s=data.sentences[n];let out;if(mode==='text')out=s.units.map(u=>'<span class="phrase" role="button" tabindex="0" data-he="'+esc(u.he)+'" aria-label="'+esc(s.en.slice(s.words[u.first].charStart,s.words[u.last-1].charEnd))+' — פירוש">'+words(s,n,u.first,u.last)+'</span>').join('');else out=words(s,n);return '<p class="sentence" data-sentence="'+n+'" lang="en" dir="ltr">'+out+'</p>'}
function fit(){const p=$('#panel');p.style.setProperty('--reading-size',mode==='sentences'?'42px':'32px');let size=mode==='sentences'?42:32;if(innerWidth<650)size=mode==='sentences'?30:27;p.style.setProperty('--reading-size',size+'px');while(p.scrollHeight>p.clientHeight+2&&size>21){size--;p.style.setProperty('--reading-size',size+'px')}}
function schedule(){if(!started||mode!=='sentences'||!$('#auto').checked||document.hidden||$('#help').open)return;status('הקראה בעוד שתי שניות.');const serial=run;timer=setTimeout(()=>{if(serial===run)play(true)},2000)}
function render(auto=false){pause();hideMeaning();index=Math.max(0,Math.min(count()-1,index));document.body.dataset.mode=mode;const rows=ids(),first=data.sentences[rows[0]],last=data.sentences[rows.at(-1)];pageRange={start:first.start,end:last.end};range={...pageRange,kind:'page'};lastSentence=rows[0];audio.currentTime=Math.max(0,first.start-.025);$('#seek').value='0';$('#elapsed').textContent='0 / '+(last.end-first.start).toFixed(0)+' שנ׳';$('#next').classList.remove('ready');$('#prev').disabled=index===0;$('#next').textContent=index===count()-1?'סיום ✓':'המשך ←';$('#counter').textContent=mode==='text'?'חלק '+(index+1)+' מתוך '+count():'משפט '+(Math.floor(index/2)+1)+' מתוך 46 · '+(index%2?'עם תרגום':'אנגלית');$('#progress').value=index+1;$('#progress').max=count();$('#jump').innerHTML=Array.from({length:mode==='text'?data.pages.length:46},(_,n)=>'<option value="'+n+'">'+(mode==='text'?'חלק ':'משפט ')+(n+1)+'</option>').join('');$('#jump').value=String(mode==='text'?index:Math.floor(index/2));$('#tabs').hidden=mode!=='text';$('#tabs').innerHTML=mode==='text'?data.pages.map((p,n)=>'<button role="tab" id="tab-'+n+'" aria-controls="panel" aria-selected="'+(n===index)+'" tabindex="'+(n===index?0:-1)+'" data-tab="'+n+'" class="'+((saved.completed||[]).includes(n)?'done':'')+'">'+(n+1)+'</button>').join(''):'';$('#panel').setAttribute('role',mode==='text'?'tabpanel':'group');if(mode==='text')$('#panel').setAttribute('aria-labelledby','tab-'+index);else{$('#panel').removeAttribute('aria-labelledby');$('#panel').setAttribute('aria-label',$('#counter').textContent)}$('#panel').innerHTML=rows.map(sentence).join('')+(mode==='sentences'?'<p class="sentenceTranslation '+(index%2?'':'concealed')+'" lang="he" dir="rtl" '+(index%2?'':'aria-hidden="true"')+'>'+esc(first.he)+'</p>':'');$('#panel').scrollTop=0;$('#replaySelect').innerHTML=rows.map(n=>'<option value="'+n+'">משפט '+(n+1)+'</option>').join('');$('#replaySelect').value=String(rows[0]);document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('#autobox').hidden=mode!=='sentences';$('#meaningLabel').textContent=mode==='text'?'תרגום ביטוי':'תרגום מילה';$('#scene').hidden=mode!=='text';$('#scene img').src='assets/library.webp';$('#nextSentence').hidden=mode!=='sentences';const url=new URL(location);url.searchParams.set('mode',mode);url.hash=String(index+1);history.replaceState(null,'',url);persist();status(mode==='sentences'?'התרגום המלא נחשף בשקף הבא.':'בחרו חלק; ההקראה נעצרת בסופו.');fit();requestAnimationFrame(()=>{$('#tabs [aria-selected="true"]')?.scrollIntoView({block:'nearest',inline:'nearest'});fit()});if(auto)schedule()}
function navigate(delta){if(index+delta>=count()){pause();status('סיימתם את הקריאה. אפשר לעבור לשאלות ולראיות ביחידה.');$('#finish').showModal();return}if(index+delta<0)return;index+=delta;render(mode==='sentences');if(mode==='text'&&delta>0&&started)play(true)}
$('#play').onclick=()=>{if(!audio.paused||timer){pause();timer=0;status('ההקראה הושהתה. לחצו שוב כדי להמשיך.')}else play()};$('#restart').onclick=()=>play(true);$('#replay').onclick=()=>{const n=Number($('#replaySelect').value),s=data.sentences[n];lastSentence=n;play(true,{start:s.start,end:s.end,kind:'sentence'})};$('#prev').onclick=()=>navigate(-1);$('#next').onclick=()=>navigate(1);$('#nextSentence').onclick=()=>{index=Math.min(count()-1,2*(Math.floor(index/2)+1));render(true)};$('#jump').onchange=()=>{index=Number($('#jump').value)*(mode==='sentences'?2:1);render(false)};
$('#speed').onchange=()=>{speed=Number($('#speed').value);audio.playbackRate=speed;write(rateKey,speed)};$('#auto').onchange=()=>{if(!$('#auto').checked){clearTimeout(timer);timer=0;status('הקראה אוטומטית כבויה.')}};
$('#seek').oninput=()=>{clearTimeout(timer);timer=0;range={...pageRange,kind:'page'};audio.currentTime=pageRange.start+(pageRange.end-pageRange.start)*Number($('#seek').value)/1000;sync()};$('#seek').onchange=()=>{if(!audio.paused&&audio.currentTime>=pageRange.end-.02)finish()};
$('#tabs').onclick=e=>{const b=e.target.closest('[data-tab]');if(b){index=Number(b.dataset.tab);render(false)}};$('#tabs').onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();e.stopPropagation();index=e.key==='Home'?0:e.key==='End'?count()-1:Math.max(0,Math.min(count()-1,index+(e.key==='ArrowLeft'?1:-1)));render(false);$('#tabs [aria-selected="true"]').focus()}};
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(mode===b.dataset.mode)return;persist();mode=b.dataset.mode;index=Number.isInteger(saved[mode])?saved[mode]:0;render(false)});
$('#helpOpen').onclick=()=>{pause();$('#help').showModal()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#startOver').onclick=()=>{index=0;render(false);$('#help').close()};$('#reset').onclick=()=>{pause();write(stateKey+'-backup',saved);saved={text:0,sentences:0,completed:[]};index=0;persist();render(false);status('התקדמות הקריאה אופסה. המהירות לא השתנתה. ניתן לשחזר בתפריט.')};$('#restore').onclick=()=>{const back=read(stateKey+'-backup',null);if(back&&typeof back==='object'){saved=back;index=Number.isInteger(saved[mode])?saved[mode]:0;render(false);status('התקדמות הקריאה שוחזרה.')}};
document.addEventListener('keydown',e=>{if($('#help').open||$('#finish').open||e.altKey||e.ctrlKey||e.metaKey||e.target.matches('input,select,textarea')||e.target.closest('#tabs'))return;if(['ArrowRight','ArrowUp','ArrowLeft','ArrowDown'].includes(e.key)){e.preventDefault();navigate(['ArrowRight','ArrowUp'].includes(e.key)?-1:1)}else if(e.key==='Escape')hideMeaning()});
let touch=null;$('#panel').addEventListener('touchstart',e=>{if(e.touches.length===1)touch=[e.touches[0].clientX,e.touches[0].clientY]}, {passive:true});$('#panel').addEventListener('touchend',e=>{if(!touch)return;const d=e.changedTouches[0],dx=d.clientX-touch[0],dy=d.clientY-touch[1];touch=null;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.5)navigate(dx<0?1:-1)},{passive:true});
let wheel=0;$('#panel').addEventListener('wheel',e=>{if(Math.abs(e.deltaX)>65&&Math.abs(e.deltaX)>Math.abs(e.deltaY)*1.5&&Date.now()-wheel>500){wheel=Date.now();navigate(e.deltaX>0?1:-1)}},{passive:true});
document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();status('ההקראה נעצרה במעבר מהדף.')}});window.addEventListener('pagehide',pause);window.addEventListener('storage',e=>{if(e.key==='teachers-read-alone-audio-owner-v1'&&e.newValue!==owner)pause();if(e.key===rateKey){const value=Number(e.newValue);if(rates.includes(value)){speed=value;audio.playbackRate=speed;$('#speed').value=String(speed)}}});window.addEventListener('resize',()=>{if(data)fit()});
fetch('content.json?v=g9-read-alone-20260922').then(r=>{if(!r.ok)throw Error(r.status);return r.json()}).then(d=>{data=d;audio.src=d.audio;audio.load();const hash=parseInt(location.hash.slice(1),10);index=Number.isFinite(hash)?hash-1:Number.isInteger(saved[mode])?saved[mode]:0;for(const b of document.querySelectorAll('[data-ready]'))b.disabled=false;render(false);window.READ_ALONE_QA={get data(){return data},get mode(){return mode},get index(){return index},get range(){return range},get rate(){return speed},get pending(){return !!timer},setPage:(n,m=mode)=>{mode=m;index=n;render(false)},sync,pause};}).catch(e=>status('הקריאה לא נטענה. רעננו את הדף או חזרו לטקסט המקורי ביחידה.'));
})();
