const S=TEACHER;let i=Math.max(0,Math.min(S.length-1,(parseInt(location.hash.slice(1))||1)-1));const main=document.querySelector('main');function go(n){i=Math.max(0,Math.min(S.length-1,n));main.innerHTML='<article><p class="eyebrow">Unit 2 · Meeting guide</p><h1>'+S[i].title+'</h1><p class="mini" lang="he" dir="rtl">נוצר: יום שלישי, י״א בתשרי תשפ״ז (22.9.2026)</p>'+S[i].body+'</article>';main.scrollTop=0;document.querySelector('#count').textContent=(i+1)+' / '+S.length;document.querySelector('#back').disabled=i===0;document.querySelector('#next').disabled=i===S.length-1;document.querySelector('#jump').value=i;history.replaceState(null,'','#'+(i+1));}document.querySelector('#jump').innerHTML=S.map((s,n)=>'<option value="'+n+'">'+(n+1)+'. '+s.title+'</option>').join('');document.querySelector('#jump').onchange=e=>go(Number(e.target.value));document.querySelector('#back').onclick=()=>go(i-1);document.querySelector('#next').onclick=()=>go(i+1);document.addEventListener('keydown',e=>{if(e.target.closest('select'))return;if(['ArrowRight','ArrowDown','PageDown'].includes(e.key)){e.preventDefault();go(i+1)}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();go(i-1)}});let wheel=0;main.addEventListener('wheel',e=>{if(e.deltaY>0&&main.scrollTop+main.clientHeight<main.scrollHeight-3)return;if(e.deltaY<0&&main.scrollTop>3)return;e.preventDefault();if(Date.now()-wheel<500)return;wheel=Date.now();go(i+(e.deltaY>0?1:-1))},{passive:false});function installSwipe(surface,navigate){
 let gesture=null,suppressClickUntil=0;
 const scrolls=(node,dy)=>{for(let el=node;el&&el.nodeType===1;el=el.parentElement){const style=el.ownerDocument.defaultView.getComputedStyle(el);if(/auto|scroll/.test(style.overflowY)&&el.scrollHeight>el.clientHeight+3){if(dy<0&&el.scrollTop+el.clientHeight<el.scrollHeight-3)return true;if(dy>0&&el.scrollTop>3)return true;}}return false;};
 surface.addEventListener('touchstart',e=>{gesture=null;if(e.touches.length!==1||e.target.closest('input,select,textarea'))return;const t=e.touches[0];gesture={x:t.clientX,y:t.clientY,target:e.target,scroll:false};},{capture:true,passive:true});
 surface.addEventListener('touchmove',e=>{if(!gesture||e.touches.length!==1){gesture=null;return;}const t=e.touches[0],dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;if(Math.max(Math.abs(dx),Math.abs(dy))<10)return;const horizontal=Math.abs(dx)>Math.abs(dy)*1.15;if(!horizontal&&scrolls(gesture.target,dy)){gesture.scroll=true;return;}if(!gesture.scroll&&e.cancelable)e.preventDefault();},{capture:true,passive:false});
 surface.addEventListener('touchend',e=>{if(!gesture)return;const g=gesture;gesture=null;const t=e.changedTouches[0],dx=t.clientX-g.x,dy=t.clientY-g.y;if(g.scroll||Math.max(Math.abs(dx),Math.abs(dy))<45)return;const horizontal=Math.abs(dx)>Math.abs(dy)*1.15;if(!horizontal&&(Math.abs(dy)<=Math.abs(dx)*1.15||scrolls(g.target,dy)))return;if(e.cancelable)e.preventDefault();e.stopImmediatePropagation();suppressClickUntil=Date.now()+450;navigate((horizontal?dx:dy)<0?1:-1);},{capture:true,passive:false});
 surface.addEventListener('touchcancel',()=>{gesture=null;},{capture:true,passive:true});
 surface.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation();}},{capture:true});
}
installSwipe(main,d=>go(i+d));go(i);window.teacher={go,slides:S};