'use strict';
/* Teachers: 165 source entries, two fixed-position slides each, break every three. */
(async function(){
const $=id=>document.getElementById(id),stage=$('stage'),menu=$('menu');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let words=window.VOCABULARY;
if(!Array.isArray(words)){try{const r=await fetch('entries.json');if(!r.ok)throw Error(r.status);words=(await r.json()).map(w=>({...w,en:w.word,mean_he:w.meaning,ex_en:w.sentence,ex_he:w.translation}));}catch(e){stage.innerHTML='<div class="loading">לא ניתן לטעון את המילים. רעננו את הדף כשיש חיבור לאינטרנט.</div>';return;}}
if(words.length!==165||words.some(w=>!w.en||!w.ex_en||!w.ex_he||!w.mean_he)){stage.innerHTML='<div class="loading">רשימת המילים אינה מלאה. לא מוצגת גרסה חלקית.</div>';return;}
const colours=['#58e1ff','#b395ff','#ffd170','#8bebb9','#ff9089','#c8a4ff'];
const breaks=[
['Mountain lake','Snow covers the peaks above this quiet lake.','שלג מכסה את הפסגות שמעל האגם השקט הזה.','mountain',''],
['Look again','Which orange circle looks bigger?','איזה עיגול כתום נראה גדול יותר? שני העיגולים שווים בגודלם.','circles',''],
['Northern lights','Tiny particles meet gases high in the sky and make these lights.','חלקיקים זעירים פוגשים גזים בגובה רב בשמיים ויוצרים את האורות האלה.','aurora','https://spaceplace.nasa.gov/aurora/en/'],
['Desert colours','Look at the warm colours and the long shadows.','התבוננו בצבעים החמים ובצללים הארוכים.','desert',''],
['Straight or tilted?','Are the blue lines straight?','האם הקווים הכחולים ישרים? כן — הם ישרים ומקבילים.','wall',''],
['Saturn','Saturn’s rings are made mostly of water ice.','הטבעות של שבתאי עשויות בעיקר מקרח של מים.','saturn','https://science.nasa.gov/mission/cassini/science/rings/'],
['A rainbow','Sunlight and drops of water can make a rainbow.','אור השמש וטיפות מים יכולים ליצור קשת בענן.','rainbow','https://weather.metoffice.gov.uk/learn-about/weather/optical-effects/rainbows'],
['The ocean','The ocean covers more than 70% of Earth’s surface.','האוקיינוס מכסה יותר מ־70% משטח פני כדור הארץ.','ocean','https://oceanservice.noaa.gov/facts/oceanwater.html'],
['Hidden symmetry','How many arms does this snowflake have?','כמה זרועות יש לפתית השלג המצויר? שש זרועות.','snow',''],
['Waterfall','The water falls. The rocks stay still.','המים נופלים. הסלעים נשארים ללא תנועה.','waterfall',''],
['A quiet reflection','The mountains appear again in the water.','ההרים נראים שוב בתוך המים.','reflection',''],
['Circles or a spiral?','Follow one blue line with your eyes.','עקבו בעיניכם אחרי קו כחול אחד. אלה מעגלים נפרדים, לא ספירלה.','rings','']];
const svg=(body,defs='')=>`<svg viewBox="0 0 1200 760" preserveAspectRatio="xMidYMid slice" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><defs>${defs}</defs>${body}</svg>`;
const stars=()=>Array.from({length:80},(_,i)=>`<circle cx="${(i*151+41)%1200}" cy="${(i*79+15)%410}" r="${i%4===0?2:1}" fill="#eefaff" opacity="${.35+(i%5)/8}"/>`).join('');
function landscape(kind,n){
const aurora=kind==='aurora',desert=kind==='desert',ocean=kind==='ocean';
const sky=aurora?['#080b2a','#182852']:desert?['#752968','#f09b62']:ocean?['#03397d','#4fcbe8']:['#19439d','#72d9ee'];
let defs=`<linearGradient id="sky" x2="0" y2="1"><stop stop-color="${sky[0]}"/><stop offset="1" stop-color="${sky[1]}"/></linearGradient><linearGradient id="water" x2="0" y2="1"><stop stop-color="#28c5d2"/><stop offset="1" stop-color="#06498c"/></linearGradient><linearGradient id="light"><stop stop-color="#26ffc2" stop-opacity="0"/><stop offset=".5" stop-color="#2effc0"/><stop offset="1" stop-color="#c079ff" stop-opacity=".2"/></linearGradient><linearGradient id="mist" x2="0" y2="1"><stop stop-color="#fff" stop-opacity=".8"/><stop offset="1" stop-color="#5ce9f0" stop-opacity=".1"/></linearGradient>`;
let body=`<rect width="1200" height="760" fill="url(#sky)"/>`;
if(aurora)body+=stars()+`<g class="glow" opacity=".9"><path d="M-100 90Q280 370 570 100T1320 170L1240 390Q820 180 470 310T-80 190Z" fill="url(#light)"/><path d="M0 80Q420 300 790 90T1200 220" stroke="#bd86ff" stroke-width="20" fill="none" opacity=".4"/></g>`;
else body+=`<circle cx="${desert?890:940}" cy="${desert?180:116}" r="${desert?77:56}" fill="${desert?'#ffe39c':'#fff3c7'}"/><g class="drift" opacity=".3" fill="#fff"><ellipse cx="260" cy="125" rx="150" ry="28"/><ellipse cx="340" cy="103" rx="95" ry="25"/><ellipse cx="730" cy="60" rx="100" ry="22"/></g>`;
if(desert){for(let i=0;i<5;i++)body+=`<path d="M-60 ${230+i*95}Q${210+i*75} ${80+i*90} 570 ${270+i*70}T1250 ${220+i*105}V800H-60Z" fill="${['#eeb57c','#d88663','#ba5360','#883c67','#4b315c'][i]}"/>`;return svg(body,defs);}
if(ocean){body+=`<rect y="240" width="1200" height="520" fill="url(#water)"/>`;for(let i=0;i<16;i++)body+=`<path class="drift" d="M-40 ${270+i*25}Q160 ${230+i*27} 370 ${270+i*25}T800 ${270+i*25}T1240 ${270+i*25}" fill="none" stroke="${i%3?'#77e4ec':'#fff'}" opacity="${i%3?.20:.38}" stroke-width="${3+i/4}"/>`;return svg(body,defs);}
const mountains=`<path d="M-40 420L70 250 145 330 330 100 510 310 615 160 755 310 890 120 1090 340 1250 240V500H-40Z" fill="${aurora?'#152040':'#476ea6'}"/><path d="M145 330L330 100 510 310 378 258 320 197 267 272 218 266ZM755 310L890 120 1020 286 908 227 861 258 824 238Z" fill="${aurora?'#a3c3ec':'#eafaff'}"/><path d="M-40 445L155 307 310 425 465 304 620 422 790 300 990 431 1160 300 1250 425V520H-40Z" fill="${aurora?'#0b1933':'#244e78'}"/>`;
body+=mountains+`<rect y="435" width="1200" height="325" fill="url(#water)"/>`;
if(kind==='reflection'||kind==='mountain')body+=`<g transform="translate(0 875) scale(1 -0.85)" opacity=".28">${mountains}</g>`;
if(kind==='waterfall')body+=`<path d="M0 360L390 320 410 390 640 355 680 330 1200 370V590H0Z" fill="#244e61"/><path d="M430 340Q485 390 545 345L570 650Q490 695 405 645Z" fill="url(#mist)"/>`+Array.from({length:11},(_,i)=>`<path class="flow" d="M${443+i*8} 366Q${425+i*12} 470 ${413+i*14} 652" fill="none" stroke="#e5fffe" opacity=".6" stroke-width="3" stroke-dasharray="24 16"/>`).join('');
if(kind==='rainbow')body+=`<g fill="none" stroke-width="14" opacity=".78">${['#ff6680','#ffa45f','#ffe677','#75e7a0','#56c6ff','#b39aff'].map((c,i)=>`<path d="M${90+i*14} 340A${480-i*14} ${350-i*14} 0 0 1 ${1050-i*14} 340" stroke="${c}"/>`).join('')}</g>`;
for(let i=0;i<16;i++){const x=i<8?i*33:950+(i-8)*40;const h=70+(i*19)%90;body+=`<path d="M${x-24} 520L${x} ${520-h}L${x+24} 520ZM${x-18} 475L${x} ${465-h*.6}L${x+18} 475Z" fill="#072e3b"/>`;}
body+=`<path d="M0 650Q190 480 330 665T630 700T980 650T1200 600V800H0Z" fill="#06172c"/>`;return svg(body,defs);}
function art(kind,n){
if(['mountain','aurora','desert','rainbow','ocean','waterfall','reflection'].includes(kind))return landscape(kind,n);
if(kind==='saturn')return svg(`<rect width="1200" height="760" fill="#090d2a"/>${stars()}<g transform="translate(620 255) rotate(-16)"><ellipse rx="350" ry="94" fill="none" stroke="#e5bb78" stroke-width="45"/><ellipse rx="318" ry="84" fill="none" stroke="#866c97" stroke-width="8"/><circle r="156" fill="url(#planet)"/><path d="M-150 -48Q0 -8 150 -48M-155 -12Q0 28 155 -12M-150 34Q0 78 150 34" fill="none" stroke="#a26c73" stroke-width="18" opacity=".4"/><path d="M-346 2A350 94 0 0 0 346 2" fill="none" stroke="#f3d5a0" stroke-width="38"/></g>`,`<linearGradient id="planet"><stop stop-color="#ffe6b1"/><stop offset=".6" stop-color="#d9a576"/><stop offset="1" stop-color="#6b4564"/></linearGradient>`);
if(kind==='circles'){const ring=(cx,r,dist,count)=>Array.from({length:count},(_,i)=>{const a=i*2*Math.PI/count;return `<circle cx="${cx+Math.cos(a)*dist}" cy="${244+Math.sin(a)*dist}" r="${r}" fill="#70badf"/>`;}).join('');return svg(`<rect width="1200" height="760" fill="#091730"/><g class="context">${ring(350,71,146,6)}${ring(850,25,92,9)}</g><circle cx="350" cy="244" r="49" fill="#ffac48" stroke="#fff3cc" stroke-width="3"/><circle cx="850" cy="244" r="49" fill="#ffac48" stroke="#fff3cc" stroke-width="3"/><g class="measure" stroke="#e4ff70" stroke-width="3"><path d="M301 318H399M801 318H899M301 312V324M399 312V324M801 312V324M899 312V324"/></g>`);}
if(kind==='wall'){let b='<rect width="1200" height="760" fill="#0c2441"/><g class="context">';for(let row=0;row<6;row++)for(let col=-1;col<13;col++)b+=`<rect x="${col*100+(row%2)*40}" y="${45+row*55}" width="98" height="53" fill="${col%2?'#e9e9d8':'#123743'}"/>`;b+='</g>';for(let row=0;row<=6;row++)b+=`<path d="M0 ${44+row*55}H1200" stroke="#53dcff" stroke-width="4"/>`;return svg(b);}
if(kind==='snow')return svg(`<rect width="1200" height="760" fill="#092747"/>${stars()}<g transform="translate(600 245)" stroke="#81f3ff" stroke-width="9" stroke-linecap="round">${Array.from({length:6},(_,i)=>`<g transform="rotate(${i*60})"><path d="M0 0V-173M0-64L-33-93M0-64L33-93M0-114L-44-150M0-114L44-150"/></g>`).join('')}</g><circle cx="600" cy="245" r="24" fill="#e4feff"/>`);
if(kind==='rings'){let b='<rect width="1200" height="760" fill="#121836"/><g transform="translate(600 230)">';for(let i=1;i<=8;i++)b+=`<circle r="${i*23}" fill="none" stroke="${i%2?'#75e9ef':'#b99bff'}" stroke-width="7"/><circle class="context" r="${i*23}" fill="none" stroke="#101938" stroke-width="10" stroke-dasharray="${9+i*2} 20" transform="rotate(${i*12})"/>`;return svg(b+'</g>');}return landscape('mountain',n);}
const slides=[{type:'cover'},{type:'intro'}];let group=0;
words.forEach((w,i)=>{if(w.group!==group){group=w.group;slides.push({type:'group',group});}slides.push({type:'word',word:w,reveal:false,wordIndex:i},{type:'word',word:w,reveal:true,wordIndex:i});if((i+1)%3===0)slides.push({type:'break',breakIndex:((i+1)/3)-1});});slides.push({type:'end'});
let current=0,breakRevealed=false,autoAudio=false,clipMap={},speechTimer=null,token=0,lastRendered='',wheelTotal=0,wheelLock=0;
const player=new Audio();player.preload='metadata';player.setAttribute('playsinline','');
function status(text){$('status').textContent=text;}
function cancelAudio(){clearTimeout(speechTimer);token++;player.pause();try{player.currentTime=0;}catch(e){}}
function clip(w){const v=clipMap[w?.id];return v&&v.src;}
function speakCurrent(immediate=false){cancelAudio();const s=slides[current];if(s.type!=='word'||!clip(s.word))return;const mine=token;player.src=clip(s.word);speechTimer=setTimeout(()=>{if(mine!==token)return;player.play().then(()=>status('מילה ומשפט באנגלית · קריינות AI')).catch(()=>status('להשמעה, לחצו על ↻.'));},immediate?0:2000);}
function tense(text){if(/\b(was|were|worked|visited|won|called|made|needed|saw|tried|helped|lived|happened)\b/i.test(text))return 'עבר';if(/\bwill\b/i.test(text))return 'עתיד';if(/\b(is|are|am|needs|reads|covers|spreads|goes)\b/i.test(text))return 'הווה';return '';}
function highlighted(text,term){const s=escape(text),t=escape(term);if(!t||/something|somebody|someone/.test(t))return s;const start=s.toLowerCase().indexOf(t.toLowerCase());if(start<0)return s;return s.slice(0,start)+'<mark>'+s.slice(start,start+t.length)+'</mark>'+s.slice(start+t.length);}
function opening(title,text,extra=''){return `<article class="screen"><div class="orbit"></div><div class="opening"><div class="eyebrow">GRADE 7 · BAND II · CORE I</div><h1>${title}</h1>${text}${extra}</div></article>`;}
function render(s){
if(s.type==='cover')return opening('ברוכים הבאים','<p>כיתה ז׳2 · אנגלית</p><p class="english">Band II · Groups 03–05</p>','<div class="actions"><button class="action" data-go="1">פתיחת המצגת</button><button class="action" id="resume">המשך מהמקום ששמרתי</button></div>');
if(s.type==='intro')return opening('מילה, משפט, משמעות','<p>קודם קוראים ומנסים להבין. בשקף הבא חושפים את התרגום.</p><p>אחרי שלושה ערכים — התנחתא חזותית קצרה.</p><p>165 ערכים בשלוש קבוצות. החומר מיועד למספר מפגשים.</p>');
if(s.type==='group')return opening(`קבוצה ${String(s.group).padStart(2,'0')}`,`<p>55 ערכים · מילה ומשפט בכל זוג שקפים</p><p>קוראים לפני שחושפים את התרגום.</p>`);
if(s.type==='word'){const w=s.word;return `<article class="screen word-screen ${s.reveal?'revealed':''}" data-entry="${w.id}" style="--accent:${colours[s.wordIndex%colours.length]}"><div class="word-layout"><div class="meta"><span>GROUP ${String(w.group).padStart(2,'0')} · ${w.number}/55</span><span class="tense">${tense(w.ex_en)}</span></div><h1 class="word ${w.en.length>17?'long':''}" data-original="word" lang="en">${escape(w.en)} <span class="pos">${escape(w.pos)}</span></h1><p class="meaning reveal-layer" aria-hidden="${!s.reveal}">${escape(w.mean_he)}</p><p class="example" data-original="sentence" lang="en">${highlighted(w.ex_en,w.en)}</p><p class="translation reveal-layer" aria-hidden="${!s.reveal}">${escape(w.ex_he)}</p></div></article>`;}
if(s.type==='break'){const b=breaks[s.breakIndex%breaks.length],isIllusion=['circles','wall','rings'].includes(b[3]);const diagram=['circles','wall','rings','snow','saturn'].includes(b[3]);const graphic=diagram?art(b[3],s.breakIndex).replace('viewBox="0 0 1200 760"','viewBox="0 0 1200 470"').replace('xMidYMid slice','xMidYMid meet'):art(b[3],s.breakIndex);return `<article class="screen break-screen ${diagram?'diagram':''}"><div class="art">${graphic}</div><div class="break-tools">${isIllusion?'<button id="measure">הסתרת הרקע להשוואה</button>':''}${b[4]?`<a href="${b[4]}" target="_blank" rel="noopener">Source</a>`:''}</div><div class="break-overlay"><div class="break-head"><h2 lang="en">${escape(b[0])}</h2><span class="break-label">התנחתא ${s.breakIndex+1} · איור, לא צילום</span></div><p class="break-en" data-original="break" lang="en">${escape(b[1])}</p><p class="break-he reveal-layer" aria-hidden="true">${escape(b[2])}</p></div></article>`;}
return opening('סיימנו את שלוש הקבוצות','<p>בחרו שלוש מילים ותרגמו משפט אחד מעברית לאנגלית.</p><p>לתרגול נוסף משתמשים בקבוצות המילים באתר הלמידה.</p>',`<div class="actions"><a class="action" href="https://englishfornoar.co.il/band-ii/groups/group-03.html" target="_blank" rel="noopener">תרגול קבוצה 03</a><button data-copy="https://englishfornoar.co.il/band-ii/groups/group-03.html">העתקת קישור</button><a class="action" href="https://englishfornoar.co.il/band-ii/groups/group-04.html" target="_blank" rel="noopener">תרגול קבוצה 04</a><button data-copy="https://englishfornoar.co.il/band-ii/groups/group-04.html">העתקת קישור</button><a class="action" href="https://englishfornoar.co.il/band-ii/groups/group-05.html" target="_blank" rel="noopener">תרגול קבוצה 05</a><button data-copy="https://englishfornoar.co.il/band-ii/groups/group-05.html">העתקת קישור</button></div>`);}
function fit(){const elements=stage.querySelectorAll('.word,.example,.meaning,.translation');elements.forEach(el=>{el.style.fontSize='';});elements.forEach(el=>{const max=el.parentElement.getBoundingClientRect();let size=parseFloat(getComputedStyle(el).fontSize),tries=0;const allocation={word:0.29,example:0.28,meaning:0.13,translation:0.23};const part=Object.keys(allocation).find(k=>el.classList.contains(k)),allowed=(max.height-50)*allocation[part];while((el.scrollWidth>el.clientWidth+1||el.getBoundingClientRect().height>allowed)&&size>16&&tries++<60){size-=1;el.style.fontSize=size+'px';}});}
function show(n,reverse=false){n=Math.max(0,Math.min(slides.length-1,n));cancelAudio();current=n;const s=slides[current];breakRevealed=reverse&&s.type==='break';
if(s.type==='word'&&lastRendered===s.word.id){const card=stage.querySelector('.word-screen');card.classList.toggle('revealed',s.reveal);card.querySelectorAll('.reveal-layer').forEach(x=>x.setAttribute('aria-hidden',String(!s.reveal)));}else{stage.innerHTML=render(s);lastRendered=s.type==='word'?s.word.id:'';fit();}
if(breakRevealed){stage.querySelector('.break-screen').classList.add('break-reveal');stage.querySelector('.break-he').setAttribute('aria-hidden','false');}
$('counter').textContent=`${current+1} / ${slides.length}`;$('progress').style.width=((current+1)/slides.length*100)+'%';document.querySelectorAll('[data-step]').forEach(b=>b.disabled=(Number(b.dataset.step)<0&&current===0)||(Number(b.dataset.step)>0&&current===slides.length-1));$('replay').disabled=s.type!=='word'||!clip(s.word);
status(s.type==='word'?(s.reveal?'התרגום נחשף — האנגלית נשארת במקומה':'קוראים ומנסים להבין לפני החשיפה'):s.type==='break'?'המעבר הבא חושף תרגום. ההתנחתא אינה מתקדמת אוטומטית.':'סווייפ שמאלה / למעלה: קדימה · ימינה / למטה: אחורה');
try{if(current>0)localStorage.setItem('teachers-grade7-unit2-band2-current',String(current));history.replaceState(null,'','#slide-'+(current+1));}catch(e){}
if(autoAudio&&s.type==='word'&&!s.reveal)speakCurrent();const measure=$('measure');if(measure)measure.onclick=()=>{const card=stage.firstElementChild;card.classList.toggle('measured');measure.textContent=card.classList.contains('measured')?'החזרת הרקע':'הסתרת הרקע להשוואה';};const resume=$('resume');if(resume)resume.onclick=()=>{let v=3;try{v=Number(localStorage.getItem('teachers-grade7-unit2-band2-current'))||3;}catch(e){}show(v);};stage.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(Number(b.dataset.go)));}
function step(d){if(menu.open)return;const s=slides[current];if(s.type==='break'&&d>0&&!breakRevealed){breakRevealed=true;stage.firstElementChild.classList.add('break-reveal');stage.querySelector('.break-he').setAttribute('aria-hidden','false');status('ממשיכים כשמוכנים.');return;}if(s.type==='break'&&d<0&&breakRevealed){breakRevealed=false;stage.firstElementChild.classList.remove('break-reveal');stage.querySelector('.break-he').setAttribute('aria-hidden','true');return;}show(current+d,d<0);}
$('contents').onclick=()=>{cancelAudio();menu.showModal();$('search').focus();};$('word-list').innerHTML=words.map(w=>`<button data-word="${w.id}">${escape(w.en)}<small>קבוצה ${w.group} · ${w.number} · ${escape(w.mean_he)}</small></button>`).join('');$('word-list').onclick=e=>{const b=e.target.closest('[data-word]');if(!b)return;menu.close();show(slides.findIndex(s=>s.type==='word'&&!s.reveal&&s.word.id===b.dataset.word));};$('search').oninput=e=>{const term=e.target.value.trim().toLowerCase();$('word-list').querySelectorAll('button').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(term));};document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>step(Number(b.dataset.step)));
window.addEventListener('keydown',e=>{if(menu.open||e.target.matches('input,select,textarea'))return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();step(1);}else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();step(-1);}else if(e.key==='Home'){e.preventDefault();show(0);}else if(e.key==='End'){e.preventDefault();show(slides.length-1);}else if(e.key.toLowerCase()==='r')speakCurrent(true);});
let pointer=null,activeTouches=new Set();stage.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;activeTouches.add(e.pointerId);if(activeTouches.size>1){pointer=null;return;}if(e.target.closest('button,a,input,select')||window.visualViewport?.scale>1)return;pointer={id:e.pointerId,x:e.clientX,y:e.clientY,time:Date.now()};});stage.addEventListener('pointerup',e=>{activeTouches.delete(e.pointerId);if(!pointer||pointer.id!==e.pointerId)return;const p=pointer;pointer=null;const dx=e.clientX-p.x,dy=e.clientY-p.y;if(Math.max(Math.abs(dx),Math.abs(dy))<44||Date.now()-p.time>1800)return;const delta=Math.abs(dx)>Math.abs(dy)?dx:dy;step(delta<0?1:-1);});stage.addEventListener('pointercancel',e=>{activeTouches.delete(e.pointerId);pointer=null;});stage.addEventListener('wheel',e=>{if(e.ctrlKey||menu.open)return;e.preventDefault();const now=Date.now();if(now<wheelLock)return;wheelTotal+=e.deltaY*(e.deltaMode===1?16:1);if(Math.abs(wheelTotal)>=55){step(wheelTotal>0?1:-1);wheelTotal=0;wheelLock=now+550;}},{passive:false});
$('motion').onclick=()=>{const disabled=document.body.classList.toggle('no-motion');$('motion').setAttribute('aria-pressed',String(!disabled));};$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>status('הדפדפן אינו מאפשר מסך מלא.'));};$('sound').onclick=()=>{autoAudio=!autoAudio;$('sound').setAttribute('aria-pressed',String(autoAudio));$('sound').textContent=autoAudio?'שמע פועל':'שמע';if(autoAudio){if(slides[current].type==='word')speakCurrent();else status('שמע יופעל אחרי שתי שניות בשקפי המילים.');}else cancelAudio();};$('replay').onclick=()=>speakCurrent(true);
window.addEventListener('resize',()=>requestAnimationFrame(fit));document.fonts?.ready.then(fit);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelAudio();});window.addEventListener('pagehide',cancelAudio);window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#slide-(\d+)$/);if(m)show(Number(m[1])-1);});
window.TeachersDeck={slides,words,show,next:()=>step(1),previous:()=>step(-1),get current(){return current;},get audio(){return player;}};const initial=location.hash.match(/^#slide-(\d+)$/);show(initial?Number(initial[1])-1:0);
for(const path of ['audio/manifest.json','audio-manifest.json']){try{const r=await fetch(path,{cache:'no-cache'});if(!r.ok)continue;const m=await r.json(),candidates=m.files||m.clips||{};const valid=words.every(w=>{const c=candidates[w.id];return c&&c.text===w.en.replace(/[.!?]+$/,'')+'. '+w.ex_en;});if(!valid)continue;clipMap=candidates;if(Object.keys(clipMap).length===165){$('sound').disabled=false;$('sound').title='קריינות AI מוקלטת מראש · אנגלית אמריקאית';$('replay').disabled=slides[current].type!=='word';break;}}catch(e){}}
if(!Object.keys(clipMap).length)$('sound').title='קובצי הקריינות עדיין לא זמינים. אין שימוש בקול הדפדפן.';
})();

document.addEventListener('click',async function(e){const b=e.target.closest('[data-copy]');if(!b)return;try{await navigator.clipboard.writeText(b.dataset.copy);document.getElementById('status').textContent='הקישור הועתק';}catch(err){document.getElementById('status').textContent=b.dataset.copy;}});
