(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const homeMode=new URLSearchParams(location.search).get('mode')==='home';const slides=homeMode?LESSON.slides.filter(s=>s.home):LESSON.slides;LESSON.sections=[...new Set(slides.map(s=>s.section))];const choices={},rateKey='teachers-read-alone-speed-v1',slideKey='teachers-unit2-'+LESSON.id+'-v1';let i=Math.max(0,Math.min(slides.length-1,(parseInt(location.hash.slice(1))||1)-1));let lastWheel=0,timer=0,frame=0,run=0,clip=null,activeWord=-1,tipWord=null;
const audio=new Audio();audio.id='sentenceAudio';audio.preload='auto';document.body.append(audio);const audioAvailable=false;const audioData=Promise.resolve(null);audioData.catch(()=>{});
let speed=.75;try{const n=Number(localStorage.getItem(rateKey));if([1,.75,.5,.35,.25].includes(n))speed=n;}catch(e){}$('#speed').value=String(speed);
function clearHighlight(){document.querySelectorAll('.spoken').forEach(w=>w.classList.remove('spoken'));activeWord=-1;}
function sync(){if(audio.paused||!clip)return clearHighlight();const n=clip.words.findIndex(w=>audio.currentTime>=w.start&&audio.currentTime<w.end);if(n===activeWord)return;clearHighlight();document.querySelector(`[data-word="${n}"]`)?.classList.add('spoken');activeWord=n;}
function stop(){run++;clearTimeout(timer);cancelAnimationFrame(frame);audio.pause();clearHighlight();$('#speak').textContent='▶ הקראה';}
async function speak(n,last=n){if(!audioAvailable)return;stop();const currentRun=run;try{const data=await audioData;if(currentRun!==run||document.hidden||$('#menu').open)return;clip={start:data.sentences[n].start,end:data.sentences[last].end,words:data.sentences.slice(n,last+1).flatMap(s=>s.words)};if(!audio.src)audio.src=data.audio;audio.currentTime=Math.max(0,clip.start-.025);audio.playbackRate=speed;audio.preservesPitch=true;await audio.play();if(currentRun!==run){audio.pause();return;}$('#speak').textContent='❚❚ עצירה';function watch(){if(currentRun!==run)return;sync();if(audio.currentTime>=clip.end+.025){stop();document.querySelector('#readerContinue')?.classList.add('pulse');return;}frame=requestAnimationFrame(watch);}watch();}catch(e){if(currentRun===run)$('#speak').textContent='▶ לחצו להקראה';}}
audio.addEventListener('timeupdate',()=>{sync();if(clip&&audio.currentTime>=clip.end+.025){stop();document.querySelector('#readerContinue')?.classList.add('pulse');}});audio.addEventListener('pause',clearHighlight);audio.addEventListener('ended',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});window.addEventListener('pagehide',stop);
$('#speed').onchange=()=>{speed=Number($('#speed').value);audio.playbackRate=speed;try{localStorage.setItem(rateKey,speed);}catch(e){}};$('#speak').onclick=()=>{if(!audio.paused)stop();else if(slides[i].kind==='sentence')speak(slides[i].n);else if(slides[i].kind==='reader')speak(slides[i].ids[0],slides[i].ids.at(-1));};
function hideTip(){tipWord?.removeAttribute('aria-describedby');tipWord=null;$('#wordTooltip').hidden=true;}
function showTip(word){hideTip();tipWord=word;const tip=$('#wordTooltip');tip.textContent=word.dataset.he;tip.hidden=false;word.setAttribute('aria-describedby','wordTooltip');const a=word.getBoundingClientRect(),b=tip.getBoundingClientRect();tip.style.left=Math.max(8,Math.min(innerWidth-b.width-8,a.left+(a.width-b.width)/2))+'px';tip.style.top=(a.top-b.height-10>=8?a.top-b.height-10:a.bottom+10)+'px';}
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.sentenceWord'))hideTip();});window.addEventListener('resize',hideTip);$('#stage').addEventListener('scroll',hideTip,{passive:true});
const table=(rows,headers)=>`<div class="tableWrap"><table>${headers?`<thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead>`:''}<tbody>${rows.map(row=>`<tr>${row.map((x,n)=>n===0?`<th scope="row">${esc(x)}</th>`:`<td lang="en">${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
function questionText(s){if(!s.q.includes('___'))return esc(s.q);const width=Math.max(3,...s.opts.map(x=>x.length))+.6;return esc(s.q).replace('___',`<span class="answerGap" style="min-width:${width}ch"><span ${s.reveal?'class="hidden" aria-hidden="true"':''}>___</span><span ${s.reveal?'':'class="hidden" aria-hidden="true"'}>${esc(s.opts[s.correct])}</span></span>`);}
async function copyGroup(button){const group=String(button.dataset.copyGroup).padStart(2,'0'),url=`https://englishfornoar.co.il/band-ii/groups/group-${group}.html`,status=button.closest('.vocabItem').querySelector('.copyStatus');status.textContent='';let copied=false;
try{await navigator.clipboard.writeText(url);copied=true;}catch(e){const field=document.createElement('textarea');field.value=url;field.setAttribute('readonly','');field.style.cssText='position:fixed;top:0;left:0;opacity:0;pointer-events:none';document.body.append(field);field.select();try{copied=document.execCommand('copy');}catch(e){}field.remove();button.focus({preventScroll:true});}
if(!button.isConnected)return;
if(copied){status.textContent='✓ הקישור הועתק';}else{status.textContent='העתקה אוטומטית נחסמה. אפשר להעתיק ידנית.';$('#copyUrl').value=url;$('#copyDialog').showModal();$('#copyUrl').focus();$('#copyUrl').select();}}
function render(){stop();hideTip();const s=slides[i];document.body.classList.toggle('past',s.tense==='עבר');$('#stage').scrollTop=0;const title=`<p class="eyebrow">${esc(s.title)}</p>`,tense=`<p class="tense">${esc(s.tense||'')}</p>`;let c='';
$('#meaningLens').textContent=homeMode?'חזרה בבית · קראו, נסו ובדקו':'Unit 2 · '+LESSON.subtitle;
$('.brand').textContent='כיתה ז׳ · Unit 2';
if(s.kind==='cover')c=title+'<h1>'+esc(s.title)+'</h1><p class="sub">'+esc(s.sub)+'</p><p class="created">טיוטה לעיון המורה · Core I · קבוצות 03–05</p><div class="actions"><button id="start">מתחילים</button><a href="../index.html">כל היחידה</a></div>';
else if(s.kind==='example')c=title+tense+'<p class="hero english">'+esc(s.en)+'</p><p class="translation '+(s.reveal?'':'hidden')+'" '+(s.reveal?'':'aria-hidden="true"')+'>'+esc(s.he)+'</p>';
else if(s.kind==='plan')c=`<h2>${esc(s.title)}</h2><ol class="stepList">${s.steps.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`;
else if(s.kind==='sentence'){const words=LESSON.sentences[s.n].words;c=`${title}${tense}<p class="hero english"><span class="sentenceWords">${words.map((w,n)=>`<span class="sentenceWord" data-word="${n}" data-he="${esc(w.he)}" tabindex="0" role="button" aria-label="${esc(w.word)} — פירוש">${esc(w.word)}</span>`).join(' ')}</span></p><p class="translation ${s.reveal?'':'hidden'}" ${s.reveal?'':'aria-hidden="true"'}>${esc(s.he)}</p>`;}
else if(s.kind==='rule')c=`${title}${tense}<p class="formula english">${esc(s.formula)}</p><p class="explanation">${esc(s.he)}</p>${s.rows?table(s.rows):''}`;
else if(s.kind==='quiz'){const qid=s.reveal?i-1:i,pick=choices[qid],tone=!s.reveal?'pending':pick===undefined?'pending':pick===s.correct?'success':'wrong',status=!s.reveal?'בחרו תשובה ונמקו. הפתרון בשקף הבא.':pick===undefined?'לא נבחרה תשובה — בודקים יחד':pick===s.correct?'✓ נכון! כל הכבוד.':'✗ צריך לתקן — השוו לתשובה הנכונה';c=`<div class="banner ${tone}" role="status">${status}</div>${title}${tense}<p class="context">${esc(s.context)}</p><p class="hero" dir="auto">${questionText(s)}</p><div class="options">${s.opts.map((o,n)=>`<button class="option ${pick===n?'selected':''} ${s.reveal&&s.correct===n?'correct':''} ${s.reveal&&pick===n&&pick!==s.correct?'wrong':''}" data-choice="${n}" ${s.reveal?'disabled':''} aria-pressed="${pick===n}"><span dir="auto">${esc(o)}</span><span class="choiceLabel">${s.reveal?(n===s.correct?(n===pick?'✓ בחרתם נכון':'✓ התשובה הנכונה'):n===pick?'✗ הבחירה שלכם':' '):pick===n?'הבחירה שלכם':' '}</span></button>`).join('')}</div>${s.reveal?`<div class="feedback"><p>התשובה שלכם: <bdi dir="auto">${pick===undefined?'לא נבחרה תשובה':esc(s.opts[pick])}</bdi></p><p class="correctText">✓ התשובה הנכונה: <bdi dir="auto">${esc(s.opts[s.correct])}</bdi></p><p>${esc(s.why)}</p>${s.evidence?`<p class="evidence english">${esc(s.evidence)}</p>`:''}<div class="actions"><button id="retry">ניסיון נוסף</button><button id="continue">המשך ←</button></div></div>`:'<div class="actions"><button id="check">בדיקת התשובה ←</button></div>'}`;}
else if(s.kind==='reader'){
 const tabs=slides.map((x,n)=>({...x,pos:n})).filter(x=>x.kind==='reader'&&x.title===s.title);let word=0;
 c=`<p class="eyebrow">${esc(s.title)}</p><div class="readerTabs" role="tablist" aria-label="חלקי הקריאה">${tabs.map((x,n)=>`<button role="tab" aria-selected="${x.pos===i}" aria-controls="readPanel" data-tab="${x.pos}" class="${n<s.tab?'done':''}">${n+1}</button>`).join('')}</div><div id="readPanel" role="tabpanel" class="english">${s.ids.map(id=>`<p>${LESSON.sentences[id].words.map(w=>`<span class="sentenceWord" data-word="${word++}" data-he="${esc(w.he)}" tabindex="0" role="button" aria-label="${esc(w.word)} — פירוש">${esc(w.word)}</span>`).join(' ')}</p>`).join('')}</div><div class="readerControls"><button id="readerReplay" ${audioAvailable?'':'disabled'}>${audioAvailable?'▶ הקראת החלק':'הקראה בהכנה'}</button><button id="readerContinue">המשך ←</button></div><p class="readerCount">חלק ${s.tab+1} מתוך ${s.tabs} · נגיעה במילה לפירוש</p>`;
}
else if(s.kind==='worksheet')c=`${title}<p class="writingInstruction">מלאו עכשיו רק את משימה ${s.number} בדף Part ${s.part}. ${esc(s.instruction)} ${s.number===1?'':s.number===3?'כתבו בדף את המשפט השלם.':'כתבו בדף רק את המילה או הביטוי שבחרתם.'}</p><p class="worksheetVocab" dir="auto">${esc(s.vocab)}</p><div class="writingItems">${s.items.map((x,n)=>`<div><p>${s.number}.${n+1} · ${esc(x.he)}</p><p class="english">${esc(x.en)}</p></div>`).join('')}</div><p class="sub">לא חוזרים למשימות קודמות. ממשיכים יחד לפי הנחיית המורה.</p>`;
else if(s.kind==='collect')c=`<h2>${esc(s.title)}</h2><p class="explanation">${esc(s.sub)}</p><p class="sub">בשקפים הבאים: פתרון והסבר לכל פריט.</p>`;
else if(s.kind==='worksheetAnswer')c=`${title}<p class="sub">${esc(s.he)}</p><p class="formula english">${esc(s.answer)}</p><div class="feedback">✓ ${esc(s.why)}</div><p class="sub">השוו בעל פה: איזה רמז עזר לבחור או לסדר?</p>`;
else if(s.kind==='summary')c=`${title}${tense}${table(s.rows,['מבנה','יחיד','רבים'])}`;
else if(s.kind==='vocab')c=`<h2>${esc(s.title)}</h2><p class="sub">${esc(s.sub)}</p><div class="vocabList">${s.entries.map(e=>`<div class="vocabItem"><div class="groupReference"><a href="https://englishfornoar.co.il/band-ii/groups/group-${String(e.group).padStart(2,'0')}.html" target="_blank" rel="noopener" aria-label="פתיחת קבוצת מילים ${String(e.group).padStart(2,'0')}">קבוצה ${String(e.group).padStart(2,'0')} ↗</a><button type="button" data-copy-group="${e.group}" aria-label="העתקת קישור לקבוצה ${String(e.group).padStart(2,'0')}">העתקת קישור</button></div><span class="copyStatus" role="status" aria-live="polite"></span><bdi>${esc(e.word)}</bdi><p>${esc(e.meaning)}</p></div>`).join('')}</div>`;
else if(s.kind==='inventory')c=`${title}${tense}${table(s.items,['פריט בחדר','כמות'])}<p class="sub">${esc(s.sub)}</p>`;
else if(s.kind==='task')c=`${title}${tense}<h2>עכשיו אתם</h2><p class="explanation">${esc(s.prompt)}</p><p class="sub">נסו לפני המעבר. בשקף הבא דוגמה וכללי בדיקה.</p>`;
else if(s.kind==='review')c=`${title}${tense}<p class="sub">דוגמה אפשרית — גם ניסוח אחר שמתאים למשימה מתקבל.</p><p class="formula english">${esc(s.model)}</p><div class="feedback">${esc(s.check)}</div><div class="actions"><button id="retry">חזרה למשימה</button><button id="continue">המשך ←</button></div>`;
else if(s.kind==='reading')c=`<h2 dir="ltr">${esc(s.title)}</h2><p class="sub">${esc(s.sub)}</p><p class="hero english">${esc(s.text)}</p>`;
else if(s.kind==='pause')c=`<h2>${esc(s.title)}</h2><img src="${esc(s.image)}" alt="${esc(s.title)}" loading="lazy"><p class="sub">הפוגה קצרה · ממשיכים כשמוכנים</p>`;
else if(s.kind==='checkpoint'||s.kind==='restart')c=`<h2>${esc(s.title)}</h2><p class="explanation">${esc(s.sub)}</p><div class="actions"><button id="presentSummary">סיכום ההווה</button><button id="continue">המשך ←</button></div>`;
else c=`${title}<p class="formula english">${esc(s.text)}</p><p class="sub">${esc(s.sub)}</p>`;
$('#stage').innerHTML=`<article class="${s.kind}">${c}</article>`;$('#counter').textContent=`${i+1} / ${slides.length}`;$('#prev').disabled=i===0;$('#next').disabled=i===slides.length-1;$('#speak').disabled=!audioAvailable||!['sentence','reader'].includes(s.kind);$('#speak').textContent=audioAvailable?'▶ הקראה':'הקראה בהכנה';$('#readProgress').innerHTML=s.kind==='sentence'?`קריאה <bdi dir="ltr">${s.n+1} / ${LESSON.sentences.length}</bdi>`:esc(s.section);const pct=Math.round((i+1)/slides.length*100);$('.progress i').style.width=pct+'%';$('.progress').setAttribute('aria-valuenow',pct);
const sectionIndex=LESSON.sections.indexOf(s.section);document.querySelectorAll('[data-section]').forEach(b=>{const n=Number(b.dataset.section);b.setAttribute('aria-current',n===sectionIndex?'step':'false');b.classList.toggle('done',n<sectionIndex);});$('#sections [aria-current=step]')?.scrollIntoView({block:'nearest',inline:'center'});
history.replaceState(null,'','#'+(i+1));try{if(i>0)localStorage.setItem(slideKey,i);}catch(e){}
document.querySelectorAll('[data-copy-group]').forEach(b=>b.onclick=()=>copyGroup(b));
document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{choices[i]=Number(b.dataset.choice);render();document.querySelector(`[data-choice="${b.dataset.choice}"]`)?.focus({preventScroll:true});});
if($('#reviewStart'))$('#reviewStart').onclick=()=>go(slides.findIndex(x=>x.kind===(homeMode?'reading':'quiz')));
if($('#readerReplay'))$('#readerReplay').onclick=()=>audio.paused?speak(s.ids[0],s.ids.at(-1)):stop();
if($('#readerContinue'))$('#readerContinue').onclick=()=>go(i+1);
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>go(Number(b.dataset.tab)));
if($('#check'))$('#check').onclick=()=>go(i+1);if($('#continue'))$('#continue').onclick=()=>go(i+1);if($('#retry'))$('#retry').onclick=()=>{delete choices[i-1];go(i-1);};if($('#presentSummary'))$('#presentSummary').onclick=()=>go(slides.findIndex(x=>x.kind==='summary'&&x.tense==='הווה'));if($('#start'))$('#start').onclick=()=>go(1);if($('#resume'))$('#resume').onclick=()=>{let n=1;try{n=Number(localStorage.getItem(slideKey))||1;}catch(e){}go(n);};
if(['sentence','reader'].includes(s.kind)){document.querySelectorAll('.sentenceWord').forEach(w=>{w.onpointerenter=e=>{if(e.pointerType!=='touch')showTip(w);};w.onpointerleave=e=>{if(e.pointerType!=='touch')hideTip();};w.onfocus=()=>showTip(w);w.onblur=hideTip;w.onclick=()=>showTip(w);w.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();showTip(w);}};});if(audioAvailable&&s.kind==='sentence')timer=setTimeout(()=>speak(s.n),2000);}}
function go(n){i=Math.max(0,Math.min(slides.length-1,n));render();}
$('#prev').onclick=()=>go(i-1);$('#next').onclick=()=>go(i+1);document.addEventListener('keydown',e=>{if(e.key==='Escape')hideTip();if($('#menu').open||$('#copyDialog').open||e.target.closest('select,input,textarea'))return;if(e.target.closest('button,a')&&['Enter',' '].includes(e.key))return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();go(i+1);}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();go(i-1);}if(e.key==='Home')go(0);if(e.key==='End')go(slides.length-1);});
$('#stage').addEventListener('wheel',e=>{const el=$('#stage');if(el.scrollHeight>el.clientHeight+4){if(e.deltaY>0&&el.scrollTop+el.clientHeight<el.scrollHeight-3)return;if(e.deltaY<0&&el.scrollTop>3)return;}e.preventDefault();if(Date.now()-lastWheel<500)return;lastWheel=Date.now();go(i+(e.deltaY>0?1:-1));},{passive:false});
function installSwipe(surface,navigate){
 let gesture=null,suppressClickUntil=0;
 const scrolls=(node,dy)=>{for(let el=node;el&&el.nodeType===1;el=el.parentElement){const style=el.ownerDocument.defaultView.getComputedStyle(el);if(/auto|scroll/.test(style.overflowY)&&el.scrollHeight>el.clientHeight+3){if(dy<0&&el.scrollTop+el.clientHeight<el.scrollHeight-3)return true;if(dy>0&&el.scrollTop>3)return true;}}return false;};
 surface.addEventListener('touchstart',e=>{gesture=null;if(e.touches.length!==1||e.target.closest('input,select,textarea'))return;const t=e.touches[0];gesture={x:t.clientX,y:t.clientY,target:e.target,scroll:false};},{capture:true,passive:true});
 surface.addEventListener('touchmove',e=>{if(!gesture||e.touches.length!==1){gesture=null;return;}const t=e.touches[0],dx=t.clientX-gesture.x,dy=t.clientY-gesture.y;if(Math.max(Math.abs(dx),Math.abs(dy))<10)return;const horizontal=Math.abs(dx)>Math.abs(dy)*1.15;if(!horizontal&&scrolls(gesture.target,dy)){gesture.scroll=true;return;}if(!gesture.scroll&&e.cancelable)e.preventDefault();},{capture:true,passive:false});
 surface.addEventListener('touchend',e=>{if(!gesture)return;const g=gesture;gesture=null;const t=e.changedTouches[0],dx=t.clientX-g.x,dy=t.clientY-g.y;if(g.scroll||Math.max(Math.abs(dx),Math.abs(dy))<45)return;const horizontal=Math.abs(dx)>Math.abs(dy)*1.15;if(!horizontal&&(Math.abs(dy)<=Math.abs(dx)*1.15||scrolls(g.target,dy)))return;if(e.cancelable)e.preventDefault();e.stopImmediatePropagation();suppressClickUntil=Date.now()+450;navigate((horizontal?dx:dy)<0?1:-1);},{capture:true,passive:false});
 surface.addEventListener('touchcancel',()=>{gesture=null;},{capture:true,passive:true});
 surface.addEventListener('click',e=>{if(Date.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation();}},{capture:true});
}
installSwipe($('#stage'),delta=>go(i+delta));
const stops=LESSON.sections.map((label,n)=>({label,n:slides.findIndex(s=>s.section===label)}));
$('#sections').innerHTML=stops.map((x,n)=>`<button data-section="${n}">${esc(x.label)}</button>`).join('');document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>go(stops[Number(b.dataset.section)].n));
$('#contents').innerHTML=[...stops,...slides.map((s,n)=>({label:s.title,n,kind:s.kind})).filter(s=>s.kind==='worksheet'||s.kind==='collect')].map(x=>`<button data-go="${x.n}">${esc(x.label)}</button>`).join('');document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{$('#menu').close();go(Number(b.dataset.go));});
$('#menuBtn').onclick=()=>{stop();$('#menu').showModal();};$('#closeMenu').onclick=()=>$('#menu').close();$('#restart').onclick=()=>{Object.keys(choices).forEach(k=>delete choices[k]);$('#menu').close();go(0);};$('#fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();
$('#closeCopy').onclick=()=>$('#copyDialog').close();
window.addEventListener('hashchange',()=>{const n=(parseInt(location.hash.slice(1))||1)-1;if(n!==i)go(n);});
window.lesson={go,slides,choices};render();
})();
