from pathlib import Path
import json,html
R=Path(__file__).resolve().parents[2];O=R/'grade7/unit-2';E=html.escape
records=json.loads((O/'vocabulary/entries.json').read_text());D=json.loads((O/'content.json').read_text());reading=json.loads((O/'reading/content.json').read_text())
questions=[]
for i,r in enumerate(records):
    distractors=[]
    for p in records[i+1:]+records[:i]:
        if p['pos']==r['pos'] and p['mean_he']!=r['mean_he'] and p['mean_he'] not in distractors:distractors.append(p['mean_he'])
        if len(distractors)==2:break
    if len(distractors)<2:
        for p in records:
            if p['mean_he']!=r['mean_he'] and p['mean_he'] not in distractors:distractors.append(p['mean_he'])
            if len(distractors)==2:break
    opts=distractors[:2];correct=i%3;opts.insert(correct,r['mean_he'])
    questions.append(dict(id=r['id'],group=r['group'],word=r['en'],sentence=r['ex_en'],translation=r['ex_he'],options=opts,correct=correct))
(O/'vocabulary/practice-data.js').write_text('window.PRACTICE = '+json.dumps(questions,ensure_ascii=False)+';\n')
coverage=[dict(id=r['id'],word=r['en'],pos=r['pos'],source_sense=r['record_sense_en'] or r['record_sense_he'],presentation='vocabulary/full.html',context=r['ex_en'],retrieval='vocabulary/practice.html?set='+str(i//15),writing='One original sentence after each five items; teacher chooses additional targets.',evidence_of_mastery='Not inferred from presentation or completion alone.',editorial_correction=r.get('editorial_correction')) for i,r in enumerate(records)]
(O/'vocabulary/coverage.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2)+'\n')
shell='''<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Words in Context | Unit 2</title><link rel="stylesheet" href="../unit.css"><style>main{max-width:850px}h1{font-size:clamp(30px,7vw,52px)}.question{border:1px solid #4b7a91;border-radius:16px;background:#10283b;padding:22px;margin-top:22px}.sentence{font:700 25px/1.6 Nunito;min-height:95px}.options{display:grid;gap:10px}.options button{font-family:Heebo;text-align:right;direction:rtl}.options .selected{outline:3px solid #ffce69}.options .correct{background:#24533e}.options .wrong{background:#693943}.feedback{padding:15px;border-left:4px solid #6ce7ff;margin-top:16px}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:18px}select{max-width:100%;font-size:17px;padding:8px;color:white;background:#183b52}.writing{padding:16px;background:#15374a;margin-top:18px}textarea{width:100%;min-height:100px;font:20px Nunito;padding:12px}.english{white-space:normal}</style></head><body><main><a href="../">⌂ Unit 2</a><h1>Words in Context</h1><p>Read the sentence. Choose the meaning that fits. After five words, write a sentence of your own.</p><label>Practice set <select id="set"></select></label><p id="progress" class="meta"></p><section id="question" class="question"></section><p class="meta">Progress is saved on this device. A correct choice is practice, not a complete measure of mastery.</p></main><script src="practice-data.js"></script><script src="practice.js"></script></body></html>'''
(O/'vocabulary/practice.html').write_text(shell)
snow=D['stories'][0];boat=D['stories'][3]
listen_questions=[
 dict(q='Why does Kali stay home?',options=['The roads are dangerous.','Her class is on holiday.','She wants to ride a bicycle.'],correct=0,evidence='A snowstorm makes the roads in Anchorage dangerous.'),
 dict(q='Where is her teacher during the online lesson?',options=['In a boat.','On his couch.','On the school bus.'],correct=1,evidence='Her teacher reads a story to the class online, from his couch.'),
 dict(q='Why does Kali clear the snow?',options=['To find her school bag.','To make room for a horse.','To earn some money.'],correct=2,evidence='She wants to earn some money.')]
body='''<!doctype html><html lang="en" dir="ltr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Listen First | Unit 2</title><link rel="stylesheet" href="unit.css"><style>h1{font-size:clamp(34px,7vw,58px)}main{max-width:850px}.task{background:#10283b;border:1px solid #396780;padding:20px;border-radius:16px;margin:18px 0}audio{width:100%}.options{display:grid;gap:10px;margin:15px 0}.options label{padding:12px;border:1px solid #47728a;border-radius:8px;font:20px Nunito}.feedback{color:#dcff72;min-height:26px}textarea{width:100%;min-height:90px;font:20px Nunito;padding:12px}.transcript{font:23px/1.7 Nunito}.source{font:13px/1.5 Nunito;overflow-wrap:anywhere}</style></head><body><main><a href="./">⌂ Unit 2</a><h1>Listen First</h1><p>Listen once for the main idea. Listen again and take notes. Then answer the questions.</p><p lang="he" dir="rtl">בהאזנה הראשונה חפשו את הרעיון המרכזי. בשנייה רשמו פרטים. פתחו את התמליל רק לאחר ניסיון עצמאי.</p><section class="task"><h2>A Snow Day, a Screen and a Shovel</h2><audio id="listeningAudio" controls preload="metadata" src="reading/assets/snow-day.mp3"></audio><label>Speed <select id="speed"><option value="1">1×</option><option value="0.75">0.75×</option><option value="0.5">0.5×</option><option value="0.35">0.35×</option><option value="0.25">0.25×</option></select></label><p><label>My notes<textarea id="notes" placeholder="Who? Where? What changes?"></textarea></label></p></section>'''
for n,q in enumerate(listen_questions):
    body+='<section class="task"><h2>'+str(n+1)+'. '+E(q['q'])+'</h2><div class="options">'+''.join('<label><input type="radio" name="q'+str(n)+'" value="'+str(i)+'"> '+E(o)+'</label>' for i,o in enumerate(q['options']))+'</div><button data-check="'+str(n)+'">Check</button><p class="feedback" id="feedback'+str(n)+'" role="status"></p></section>'
body+='<section class="task"><h2>Compare two school days</h2><p>How is Kali’s day different from your normal school day? Write two sentences. Give one detail from the recording.</p><textarea aria-label="My comparison"></textarea></section><details class="task"><summary>Show the transcript</summary><p class="transcript">'+E(snow['en'])+'</p><p class="source"><a href="'+E(snow['source'])+'">Source: KTUU / Alaska’s News Source, 10 November 2023</a></p><p><a href="reading/?text=snow-day">Read with Hebrew support →</a></p></details><script>const QUESTIONS='+json.dumps(listen_questions,ensure_ascii=False)+''';document.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.check),q=QUESTIONS[n],pick=document.querySelector('input[name="q'+n+'"]:checked');document.getElementById('feedback'+n).textContent=!pick?'Choose an answer first.':Number(pick.value)===q.correct?'Correct. Evidence: '+q.evidence:'Check your answer. Evidence: '+q.evidence;});const a=document.getElementById('listeningAudio'),s=document.getElementById('speed'),key='teachers-read-alone-speed-v1';let speed=.75;try{const v=Number(localStorage.getItem(key));if([1,.75,.5,.35,.25].includes(v))speed=v;}catch(e){}a.playbackRate=speed;s.value=String(speed);s.onchange=()=>{a.playbackRate=Number(s.value);try{localStorage.setItem(key,s.value);}catch(e){}};document.addEventListener('visibilitychange',()=>{if(document.hidden)a.pause();});window.addEventListener('pagehide',()=>a.pause());</script></main></body></html>'''
(O/'listening.html').write_text(body)
print('Built 165 context questions, a coverage map and the listening activity.')
