"""Four scheduled meetings, with equal time and balanced vocabulary allocation."""
MEETINGS = [
 dict(date='2026-10-29', title='Seasons and school years', count=42,
      skills=['Find facts in a text', 'Compare school calendars', 'Describe routines with he and she'],
      goal='Compare school years and write two routine sentences.',
      reading=[('School Years Around the World','main-text.html'),('Read & Listen','reading/?text=school-calendars')],
      reading_task='Work in pairs: each pair reads one place and finds the start, end and summer holiday. Share the facts, then compare Japan with a US place.',
      grammar=('Present Simple A · slides 7–27','grammar-a/#7'),
      grammar_task='Use I/they + verb and he/she + verb-s. Work on the rules and two question pairs; finish the remaining practice at home.',
      writing=[('Workbook · page 1','files/unit2-workbook.pdf#page=1')],
      writing_task='Answer the two calendar questions and write two sentences with begins or ends. In the final four minutes, explain Japan’s summer break.',
      prep=['Bring your notebook and workbook.', 'Name the four seasons and think about your school year.'],
      home=[('Read the complete main text with audio. Check the facts collected in class.','reading/?text=school-calendars'),('Practise the remaining affirmative examples and question pairs, slides 7–27.','grammar-a/#7'),('Answer Part C on workbook page 3 and improve your two comparison sentences.','files/unit2-workbook.pdf#page=3')],
      check='Check the country fact and third-person ending separately. Japan’s summer break is inside its school year.',
      support='Assign one place per pair before sharing the whole comparison. Use starts / ends / summer holiday as prompts.',
      exit='Explain one calendar difference without copying a whole sentence.'),
 dict(date='2026-11-01', title='WhatsApp from Argentina: routines', count=41,
      skills=['Find evidence in a message', 'Describe a school journey', 'Write negative sentences'],
      goal='Describe Carlito’s routine and explain what he does and does not do.',
      reading=[('A Horse Before Class · WhatsApp','journey-horse.html'),('Read & Listen','reading/?text=horse')],
      reading_task='Read Carlito’s message. Find who travels with him and how far they travel. Compare his journey with yours.',
      grammar=('Present Simple A · slides 28–46','grammar-a/#28'),
      grammar_task='Practise do not / does not + the base verb. Contrast an action with be. Try two question pairs before checking.',
      writing=[('Workbook · page 2','files/unit2-workbook.pdf#page=2'),('Writing sheet · Part A','worksheet.html')],
      writing_task='Answer the message questions orally. Write two facts about Carlito and one true negative about your journey. Use the final four minutes to check does not + base verb.',
      prep=['Bring your calendar answers and vocabulary notes.', 'Prepare one sentence about how you get to school.'],
      home=[('Replay the horse message. Answer the workbook page 2 questions in writing.','reading/?text=horse'),('Finish the negative-sentence practice, slides 28–46.','grammar-a/#28'),('Use Writing sheet Part A: write your routine, a friend’s routine and one negative.','worksheet.html')],
      check='Require the correct negative meaning and base verb; does not rides is not correct.',
      support='Say I ride → he rides → he does not ride. Then ask for a different example.',
      exit='Write one true does not sentence without a model.'),
 dict(date='2026-11-05', title='Email from India: questions and teamwork', count=41,
      skills=['Explain details from a message', 'Ask do/does questions', 'Give short answers and report a partner’s answer'],
      goal='Explain how Samuel travels and ask a partner about a routine.',
      reading=[('Four Kilometres Together · email','journey-wheelchair.html'),('Read & Listen','reading/?text=wheelchair')],
      reading_task='Read Samuel’s email. Find how his brothers help and how far they travel. Explain each answer using a detail from the message.',
      grammar=('Present Simple B · slides 1–17','grammar-b/#1'),
      grammar_task='Build do/does questions and short answers. Reorder a question and ask it before checking the answer.',
      writing=[('Workbook · page 4','files/unit2-workbook.pdf#page=4'),('Writing sheet · Part B','worksheet.html')],
      writing_task='Write two questions for a partner and record the answers. Use the final four minutes to correct one question independently.',
      prep=['Bring your negative sentences and vocabulary notes.', 'Think of a question you want to ask about someone’s journey.'],
      home=[('Replay the email and finish the reading questions on workbook page 4.','reading/?text=wheelchair'),('Finish the do/does practice and short answers, slides 1–17.','grammar-b/#1'),('Write three questions and short answers in Writing sheet Part B.','worksheet.html')],
      check='Questions need the correct auxiliary and base verb. Check meaning before spelling.',
      support='Rehearse a short answer orally, then write it. Refer to Samuel’s documented routine, not a claim about his life today.',
      exit='Write and answer a new Does ...? question.'),
 dict(date='2026-11-08', title='Instagram from the islands: listen and reply', count=41,
      skills=['Listen for the main idea and details', 'Ask information questions', 'Use frequency words', 'Write a relevant reply'],
      goal='Understand the boat journey and begin a reply to one of the three messages.',
      reading=[('Listen First · the school boat','listening.html'),('The School Boat · Instagram','journey-boat.html')],
      reading_task='Listen twice before opening the post. Answer the three listening questions, then read the message to check your evidence.',
      grammar=('Present Simple B · slides 18–43','grammar-b/#18'),
      grammar_task='Use where/when/how and frequency words. Select one example per rule and two checks. Practise common stative verbs in the summary.',
      writing=[('Workbook · page 6','files/unit2-workbook.pdf#page=6')],
      writing_task='Choose a sender, plan and start a 50–70-word reply. Answer the sender’s question. Use the final four minutes to check one question and one frequency sentence; finish the reply at home.',
      prep=['Bring your questions, answers and vocabulary notes.', 'Think about travelling by boat. Keep the Instagram message closed until after listening.'],
      home=[('Replay the boat recording and finish workbook page 5.','listening.html'),('Finish the information-question and frequency practice, slides 18–43.','grammar-b/#18'),('Finish and improve the 50–70-word reply on workbook page 6. Read it aloud and correct two sentences.','files/unit2-workbook.pdf#page=6')],
      check='Look for another island, five minutes and walking after the boat. A reply must address its reader’s question.',
      support='Allow replay at the learner’s speed. Provide a writing plan, then let the learner draft independently.',
      exit='Name one point to review before the exam on 12 November.'),
]
