const fs=require('fs'),path=require('path'),http=require('http'),os=require('os');
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
const root=path.resolve(__dirname,'../..'),unit=path.join(root,'grade7/unit-2'),key='teachers-unit2-meetings-v1';
const launch={executablePath:process.env.UNIT2_CHROMIUM,headless:true,args:['--no-sandbox']};
const report={viewports:[],checks:[],errors:[]},assert=(ok,msg)=>{if(!ok)throw Error(msg);};
const meetings=JSON.parse(fs.readFileSync(path.join(unit,'meetings.json'))),first=meetings[0].id,third=meetings[2].id;
const server=http.createServer((req,res)=>{let file=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(file.endsWith('/'))file+='index.html';try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.ttf':'font/ttf','.pdf':'application/pdf','.mp3':'audio/mpeg'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
const state=p=>p.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);
(async()=>{
 assert(meetings.map(m=>m.date).join(',')==='2026-10-29,2026-11-01,2026-11-05,2026-11-08','Calendar excludes trip and exam');
 assert(meetings.map(m=>m.count).join(',')==='42,41,41,41','Even vocabulary allocation');
 const ids=meetings.flatMap(m=>m.vocabularyIds),source=JSON.parse(fs.readFileSync(path.join(unit,'vocabulary/entries.json')));
 assert(JSON.stringify(ids)===JSON.stringify(source.map(w=>w.id)),'All 165 source records, exactly once and in order');
 for(const m of meetings){assert(m.timing.reduce((s,x)=>s+x[0],0)===64&&m.activities.reduce((s,x)=>s+x.minutes,0)===64,'64 class minutes');assert(m.homeActivities.reduce((s,x)=>s+x.minutes,0)===45,'45 home minutes');assert(JSON.stringify(m.homeActivities.flatMap(a=>a.vocabularyIds))===JSON.stringify(m.vocabularyIds),'Home review covers the exact class batch');}
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/grade7/unit-2/`,browser=await chromium.launch(launch);
 for(const [width,height] of [[1366,900],[390,844],[360,640]]){
  const c=await browser.newContext({viewport:{width,height},isMobile:width<700,hasTouch:true,permissions:['clipboard-read','clipboard-write']}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));
  for(const file of ['','student-preparation.html','earlier-meetings.html','earlier-preparation.html','meeting-guide.html']){await p.goto(base+file);await p.evaluate(()=>document.fonts.ready);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Overflow ${file} ${width}`);for(const href of await p.locator('a[href]').evaluateAll(a=>a.map(x=>x.getAttribute('href')))){const u=new URL(href,base+file);if(u.origin!==new URL(base).origin)continue;let local=path.join(root,decodeURIComponent(u.pathname));if(local.endsWith('/'))local+='index.html';assert(fs.existsSync(local),'Missing local link '+href);}}
  await p.goto(base+'#'+first);assert(await p.locator('[data-meeting]').count()===4,'Four dated meetings');assert(await p.locator('[data-classwork] [data-complete]').count()===16,'16 class checkboxes');assert(await p.locator('[data-homework] [data-complete]').count()===12,'12 home checkboxes');
  assert(await p.locator('#restore-history').isDisabled(),'Initially nothing to restore');
  await p.locator(`[data-complete="${first}-vocab"]`).check();assert(await p.locator(`[data-open-status="${first}-vocab-link-0"]`).isHidden(),'Completing does not open');
  await p.locator(`[data-open-id="${first}-guide"]`).click();await p.waitForURL('**/meeting-guide.html#1');await p.goBack();assert(await p.locator(`[data-open-status="${first}-guide"]`).isVisible(),'Open marker persists after return');
  await p.locator(`[data-complete-meeting="${first}"]`).check();assert(await p.locator(`#${first} [data-classwork] input:checked`).count()===4,'Class bulk completion');assert(await p.locator(`#${first} [data-homework] input:checked`).count()===0,'Class completion does not complete homework');
  await p.locator(`[data-complete="${first}-home-1"]`).check();await p.reload();assert(await p.locator(`[data-complete="${first}-home-1"]`).isChecked(),'Home completion persists');assert(await p.locator('#overall-progress').innerText()==='1 of 4 meetings completed','Dynamic meeting count');
  await p.evaluate(()=>document.fonts.ready);const requests=[],capture=r=>requests.push(r.url());p.on('request',capture);await p.locator('#reset-history').click();await p.waitForTimeout(100);p.off('request',capture);assert(!requests.length,'Reset sends no network requests');assert(await p.locator(`[data-open-status="${first}-guide"]`).isHidden(),'Reset clears opened marker');assert(await p.locator(`[data-complete="${first}-home-1"]`).isChecked(),'Reset preserves homework');
  await p.reload();await p.locator('#restore-history').focus();await p.keyboard.press('Enter');assert(await p.locator(`[data-open-status="${first}-guide"]`).isVisible(),'Keyboard restore after reload');
  await p.locator('#reset-history').click();await p.locator(`[data-open-id="${first}-prep"]`).click();await p.waitForURL('**/student-preparation.html#'+first);assert(await p.locator(`[data-complete="${first}-home-1"]`).isChecked(),'Same home state on preparation page');await p.locator(`[data-ready="${first}"]`).check();await p.locator(`[data-complete="${first}-home-2"]`).check();
  if(width===1366){await p.locator(`#${first} > .group-link [data-copy]`).first().click();assert(await p.evaluate(()=>navigator.clipboard.readText())==='https://englishfornoar.co.il/band-ii/groups/group-03.html','Exact group clipboard');}
  await p.goto(base+'#'+first);await p.locator('#reset-history').click();await p.reload();await p.locator('#restore-history').click();const restored=await state(p);assert(restored.opened[first+'-guide']&&restored.opened[first+'-prep'],'Repeated reset restores old and new visits');assert(restored.ready[first]&&restored.completed[first+'-home-2'],'Ready and home progress preserved');
  const second=await c.newPage();await second.goto(base+'#'+first);await p.locator('#reset-history').click();await second.waitForFunction(()=>!document.querySelector('#restore-history').disabled);assert(await second.locator(`[data-open-status="${first}-guide"]`).isHidden(),'Reset reaches other tab');await second.locator('#restore-history').click();await p.waitForFunction(id=>document.querySelector('[data-open-id="'+id+'-guide"]').classList.contains('was-opened'),first);await second.close();
  await p.locator('#continue-meeting').click();assert(await p.locator('#'+meetings[1].id).evaluate(e=>e.open),'Continue opens next unfinished date');
  await p.goto(base+'meeting-guide.html#7');assert((await p.locator('h1').innerText()).includes('05 Nov 2026'),'Guide opens matching date');
  const guide=await p.evaluate(()=>{const issues=[];for(let i=0;i<teacher.slides.length;i++){teacher.go(i);const m=document.querySelector('main');if(document.documentElement.scrollWidth>innerWidth+1||m.scrollWidth>m.clientWidth+1||m.getBoundingClientRect().right>innerWidth+1)issues.push(i);m.scrollTop=m.scrollHeight;if(m.scrollTop+m.clientHeight<m.scrollHeight-1)issues.push('scroll '+i);}return {count:teacher.slides.length,issues};});assert(guide.count===12&&!guide.issues.length,`All guide slides fit ${width}: ${guide.issues}`);
  if(width===390){await p.evaluate(()=>teacher.go(0));const cdp=await c.newCDPSession(p);async function swipe(dx,dy){const m=await p.locator('main').boundingBox(),x=m.x+m.width*.5,y=m.y+m.height*.5;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let n=1;n<=6;n++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*n/6,y:y+dy*n/6}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}await swipe(-90,0);assert((await p.locator('#count').innerText()).startsWith('2 /'),'Left swipe');await swipe(90,0);assert((await p.locator('#count').innerText()).startsWith('1 /'),'Right swipe');await p.locator('main').evaluate(e=>e.scrollTop=e.scrollHeight);await swipe(0,-90);assert((await p.locator('#count').innerText()).startsWith('2 /'),'Up swipe');await p.locator('main').evaluate(e=>e.scrollTop=0);await swipe(0,90);assert((await p.locator('#count').innerText()).startsWith('1 /'),'Down swipe');await p.screenshot({path:'/tmp/unit2-dated-guide-390.png'});}
  await p.goto(base);await p.evaluate(()=>document.fonts.ready);await p.screenshot({path:`/tmp/unit2-dated-${width}.png`,fullPage:false});await p.locator('#'+first).evaluate(e=>e.open=true);await p.locator('#'+first+' [data-classwork] .activity').first().scrollIntoViewIfNeeded();await p.screenshot({path:`/tmp/unit2-dated-class-${width}.png`,fullPage:false});report.viewports.push({width,height,meetings:4,classActivities:16,homeRounds:12,guideSlides:12});await c.close();
 }
 const c=await browser.newContext(),p=await c.newPage();
 // Every home link starts and ends at the assigned item, including set/group boundaries.
 for(const m of meetings){for(const a of m.homeActivities){const url=a.links.find(x=>x.href.includes('practice.html')).href;await p.goto(base+url);assert((await p.locator('#progress').innerText()).includes('Item '+a.firstItem+' ·'),'Precise practice start');assert(await p.locator('#back').isDisabled(),'Cannot go before assigned range');for(let i=a.firstItem;i<a.lastItem;i++)await p.locator('#next').click();assert((await p.locator('#progress').innerText()).includes('Item '+a.lastItem+' ·'),'Precise practice end');assert(await p.locator('#next').isDisabled(),'Cannot run past assigned range');await p.locator('#back').click();assert((await p.locator('#progress').innerText()).includes('Item '+(a.lastItem-1)+' ·'),'Previous crosses set boundaries');}}
 const vocabLinks=new Map();for(const m of meetings)for(const a of [...m.activities,...m.homeActivities])for(const l of a.links)if(l.href.includes('full.html'))vocabLinks.set(l.href,l.title);
 for(const [href,title] of vocabLinks){await p.goto(base+href);await p.waitForFunction(()=>window.TeachersDeck);const actual=await p.evaluate(()=>TeachersDeck.slides[TeachersDeck.current].word.id),match=title.match(/Group (\d+) · entries (\d+)/);assert(actual===`g${match[1]}-${match[2].padStart(2,'0')}`,'Vocabulary link '+title);}
 await p.goto(base+'vocabulary/practice.html?set=2');assert(!(await p.locator('#set').evaluate(e=>e.parentElement.hidden)),'Old unrestricted practice still works');
 // Old state remains accessible in the archive and never completes regrouped work.
 await p.goto(base);await p.evaluate(key=>localStorage.setItem(key,JSON.stringify({version:1,opened:{'m3-message':true},completed:{'m3-message':true},ready:{m3:true},lastOpened:'m3-message',expanded:'m3',historyBackup:{opened:{'m1-vocab':true},lastOpened:'m1-vocab'}})),key);await p.reload();assert(await p.locator('[data-classwork] input:checked').count()===0,'Old completion not misapplied');await p.goto(base+'earlier-meetings.html#m3');assert(await p.locator('[data-complete="m3-message"]').isChecked(),'Earlier completion retained');assert(await p.locator('[data-open-status="m3-message"]').isVisible(),'Earlier visit retained');await p.locator('[data-open-id="m3-guide"]').click();await p.waitForURL('**/earlier-guide.html#7');assert((await p.locator('h1').innerText()).includes('Meeting 3'),'Earlier guide link preserved');await p.goto(base+'earlier-preparation.html#m3');assert(await p.locator('[data-ready="m3"]').isChecked(),'Earlier Ready retained');await c.close();
 const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=()=>{throw new DOMException('Blocked','QuotaExceededError');};});const bp=await blocked.newPage();await bp.goto(base);await bp.locator(`[data-complete="${first}-vocab"]`).check();await bp.locator(`[data-complete="${first}-reading"]`).check();assert(await bp.locator(`[data-complete="${first}-vocab"]`).isChecked(),'Blocked storage in-memory state');assert((await bp.locator('#save-status').innerText()).includes('Saving is unavailable'),'Blocked storage notice');await blocked.close();
 const clean=await browser.newContext(),cp=await clean.newPage();await cp.goto(base);assert(await cp.locator('[data-complete]:checked').count()===0,'Browser isolation');await clean.close();await browser.close();
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'unit2-dated-profile-'));let persistent=await chromium.launchPersistentContext(profile,launch),pp=await persistent.newPage();await pp.goto(base);await pp.locator(`[data-complete="${first}-vocab"]`).check();await pp.locator(`[data-open-id="${first}-guide"]`).click();await pp.waitForURL('**/meeting-guide.html#1');await pp.goBack();await pp.locator('#reset-history').click();await persistent.close();persistent=await chromium.launchPersistentContext(profile,launch);pp=await persistent.newPage();await pp.goto(base);await pp.locator('#restore-history').click();assert(await pp.locator(`[data-open-status="${first}-guide"]`).isVisible(),'History restoration after browser restart');assert(await pp.locator(`[data-complete="${first}-vocab"]`).isChecked(),'Completion after browser restart');await persistent.close();fs.rmSync(profile,{recursive:true,force:true});
 report.checks=['exact dates and equal 64-minute class/45-minute home budgets','165 records in order, exact class/home coverage','all 12 bounded home-practice ranges','all vocabulary deep links','four-direction teacher-guide swipes','separate class/home/Ready progress','legacy progress and guide archive preserved','repeated history reset/restore and cross-tab updates','browser restart and isolation','blocked-storage fallback','exact clipboard group link'];server.close();fs.writeFileSync(path.join(__dirname,'dated-meetings-qa-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(report.errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exit(1);});
