const fs=require('fs'),path=require('path'),http=require('http'),os=require('os');
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
const root=path.resolve(__dirname,'../..'),unit=path.join(root,'grade7/unit-2'),key='teachers-unit2-meetings-v1';
const launch={executablePath:process.env.UNIT2_CHROMIUM,headless:true,args:['--no-sandbox']};
const report={viewports:[],checks:[],errors:[]},assert=(ok,msg)=>{if(!ok)throw Error(msg);};
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(p.endsWith('/'))p+='index.html';try{const b=fs.readFileSync(p);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.mp3':'audio/mpeg','.ttf':'font/ttf','.pdf':'application/pdf'})[path.extname(p)]||'application/octet-stream');res.end(b);}catch{res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const base=`http://127.0.0.1:${server.address().port}/grade7/unit-2/`,b=await chromium.launch(launch),meetings=JSON.parse(fs.readFileSync(path.join(unit,'meetings.json')));
assert(meetings.length===9&&meetings.every(m=>m.activities.length===4&&m.timing.reduce((s,x)=>s+x[0],0)===72),'Nine meetings with four activities and 72 minutes');
assert(meetings.flatMap(m=>Array.from({length:m.end-m.start+1},(_,i)=>`g0${m.group}-${String(m.start+i).padStart(2,'0')}`)).length===165,'165 vocabulary entries allocated');
for(const [width,height] of [[1366,900],[390,844],[360,640]]){
 const c=await b.newContext({viewport:{width,height},isMobile:width<700,hasTouch:true,permissions:['clipboard-read','clipboard-write']}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.errors.push(`HTTP ${r.status()} ${r.url()}`);});
 await p.goto(base);await p.evaluate(()=>document.fonts.ready);assert(await p.locator('[data-complete]').count()===36,'Native activity checkboxes');assert(await p.locator('[data-complete-meeting]').count()===9,'Meeting checkboxes');
 for(const file of ['','student-preparation.html','resources.html']){await p.goto(base+file);await p.evaluate(()=>document.fonts.ready);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`Horizontal overflow ${file} ${width}`);const links=await p.locator('a[href]').evaluateAll(a=>a.map(x=>x.getAttribute('href')));for(const href of links){const url=new URL(href,base+file);if(url.origin!==new URL(base).origin)continue;let local=path.join(root,decodeURIComponent(url.pathname));if(local.endsWith('/'))local+='index.html';assert(fs.existsSync(local),`Missing local link ${href}`);}}
 await p.goto(base+'#m3');await p.locator('[data-complete="m3-message"]').check();assert(!(await p.locator('[data-open-status="m3-message"]').isVisible()),'A manual tick must not imply the link was opened');
 await p.locator('[data-open-id="m3-message"]').click();await p.waitForURL('**/journey-horse.html');await p.goBack();assert(await p.locator('[data-complete="m3-message"]').isChecked(),'Completed survives navigation back');assert((await p.locator('[data-open-status="m3-message"]').innerText()).includes('opened'),'Opened badge survives navigation');
 await p.reload();assert(await p.locator('[data-complete="m3-message"]').isChecked(),'Completed survives reload');assert(await p.locator('[data-open-id="m3-message"]').evaluate(e=>e.classList.contains('was-opened')),'Visited link colour class');
 await p.locator('[data-complete="m3-message"]').uncheck();assert(await p.locator('[data-open-status="m3-message"]').isVisible(),'Unticking preserves visit history');assert(!(await p.locator('[data-complete="m3-message"]').isChecked()),'Untick is saved');
 await p.locator('[data-complete-meeting="m3"]').check();assert(await p.locator('#m3 [data-complete]:checked').count()===4,'Bulk complete sets all four');assert((await p.locator('#overall-progress').innerText()).startsWith('1 of 9'),'Meeting total');await p.locator('[data-complete="m3-message"]').uncheck();assert(await p.locator('[data-complete-meeting="m3"]').evaluate(e=>e.indeterminate),'Partial meeting state');
 await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(150);const requests=[];const capture=r=>requests.push({method:r.method(),url:r.url(),body:r.postData()});p.on('request',capture);await p.locator('[data-complete="m3-message"]').check();await p.waitForTimeout(120);p.off('request',capture);assert(requests.length===0,'Checkbox state must generate no network request');
 await p.goto(base+'student-preparation.html#m3');await p.locator('[data-ready="m3"]').check();await p.reload();assert(await p.locator('[data-ready="m3"]').isChecked(),'Student readiness saved separately');
 if(width===1366){const link='https://englishfornoar.co.il/band-ii/groups/group-03.html';await p.locator('#m3 [data-copy]').click();assert(await p.evaluate(()=>navigator.clipboard.readText())===link,'Exact group clipboard link');}
 await p.goto(base+'meeting-guide.html#7');assert((await p.locator('h1').innerText()).includes('Meeting 3'),'Teacher guide deep link');
 const guide=await p.evaluate(()=>{const issues=[];for(let i=0;i<teacher.slides.length;i++){teacher.go(i);if(document.documentElement.scrollWidth>innerWidth+1)issues.push('horizontal '+i);const main=document.querySelector('main'),footer=document.querySelector('footer');if(main.scrollWidth>main.clientWidth+1||main.getBoundingClientRect().right>innerWidth+1)issues.push('clipped content '+i);if(main.getBoundingClientRect().bottom>footer.getBoundingClientRect().top+1)issues.push('footer '+i);main.scrollTop=main.scrollHeight;if(main.scrollTop+main.clientHeight<main.scrollHeight-1)issues.push('unreachable '+i);}return {slides:teacher.slides.length,issues};});assert(guide.slides===27&&!guide.issues.length,`Guide layout ${width}: ${guide.issues}`);
 if(width===390){await p.evaluate(()=>teacher.go(0));const cdp=await c.newCDPSession(p);async function swipe(dx,dy){const m=await p.locator('main').boundingBox(),x=m.x+m.width/2,y=m.y+m.height*.6;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=6;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/6,y:y+dy*i/6}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}await swipe(-90,0);assert((await p.locator('#count').innerText()).startsWith('2 /'),'Guide left swipe');await swipe(90,0);assert((await p.locator('#count').innerText()).startsWith('1 /'),'Guide right swipe');await p.locator('main').evaluate(e=>e.scrollTop=e.scrollHeight);await swipe(0,-70);assert((await p.locator('#count').innerText()).startsWith('2 /'),'Guide up swipe');await p.locator('main').evaluate(e=>e.scrollTop=0);await swipe(0,70);assert((await p.locator('#count').innerText()).startsWith('1 /'),'Guide down swipe');await p.locator('main').evaluate(e=>e.scrollTop=0);await p.screenshot({path:'/tmp/unit2-meeting-guide-mobile.png'});}
 await p.goto(base+'#m3');await p.screenshot({path:`/tmp/unit2-meetings-${width}.png`,fullPage:true});report.viewports.push({width,height,guideSlides:27,activities:36,privacyRequests:0});await c.close();
}
const clean=await b.newContext(),cleanPage=await clean.newPage();await cleanPage.goto(base);assert(await cleanPage.locator('[data-complete]:checked').count()===0,'Another browser context must have separate progress');await clean.close();report.checks.push('separate-browser isolation');
const blocked=await b.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Blocked','QuotaExceededError');};});const bp=await blocked.newPage();await bp.goto(base);await bp.locator('[data-complete="m1-vocab"]').check();await bp.locator('[data-complete="m1-listen"]').check();assert(await bp.locator('[data-complete="m1-vocab"]').isChecked(),'In-memory state survives unavailable storage');assert((await bp.locator('#save-status').innerText()).includes('Saving is unavailable'),'Honest storage-unavailable notice');await blocked.close();report.checks.push('unavailable-storage fallback');
const damaged=await b.newContext();await damaged.addInitScript(key=>localStorage.setItem(key,'invalid-json'),key);const dp=await damaged.newPage();await dp.goto(base);await dp.locator('[data-complete="m1-vocab"]').check();assert(await dp.locator('[data-complete="m1-vocab"]').isChecked(),'Malformed local data recovery');await damaged.close();report.checks.push('malformed-state recovery');
const links=await b.newContext(),lp=await links.newPage();for(const m of meetings){await lp.goto(base+m.activities[0].href);await lp.waitForFunction(()=>window.TeachersDeck);const identity=await lp.evaluate(()=>TeachersDeck.slides[TeachersDeck.current].word?.id);assert(identity===`g0${m.group}-${String(m.start).padStart(2,'0')}`,'Vocabulary deep link '+m.id);}await links.close();report.checks.push('all nine vocabulary start positions');await b.close();
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'unit2-meetings-profile-'));let persistent=await chromium.launchPersistentContext(profile,launch),pp=await persistent.newPage();await pp.goto(base);await pp.locator('[data-complete="m1-vocab"]').check();await persistent.close();persistent=await chromium.launchPersistentContext(profile,launch);pp=await persistent.newPage();await pp.goto(base);assert(await pp.locator('[data-complete="m1-vocab"]').isChecked(),'Progress survives closing and restarting browser');await persistent.close();fs.rmSync(profile,{recursive:true,force:true});report.checks.push('browser-restart persistence');
server.close();fs.writeFileSync(path.join(__dirname,'meetings-qa-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exit(1)});
