const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require(require.resolve('playwright',{paths:[process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES]}));
const root=path.resolve(__dirname,'../..'),report={layout:[],autoplay:0,errors:[]};const assert=(ok,msg)=>{if(!ok)report.errors.push(msg);};
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURIComponent(req.url.split('?')[0]));if(p.endsWith('/'))p+='index.html';try{const b=fs.readFileSync(p),mime={'.js':'text/javascript','.html':'text/html','.css':'text/css','.mp3':'audio/mpeg','.json':'application/json','.jpg':'image/jpeg','.ttf':'font/ttf'}[path.extname(p)]||'application/octet-stream';res.setHeader('Content-Type',mime);res.setHeader('Accept-Ranges','bytes');const m=(req.headers.range||'').match(/bytes=(\d+)-(\d*)/);if(m){const start=Number(m[1]),end=m[2]?Math.min(Number(m[2]),b.length-1):b.length-1;res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${b.length}`,'Content-Length':end-start+1});res.end(b.subarray(start,end+1));}else{res.setHeader('Content-Length',b.length);res.end(b);}}catch(e){res.statusCode=404;res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/grade7/unit-2/reading/`;const b=await chromium.launch({executablePath:process.env.UNIT2_CHROMIUM,headless:true,args:['--no-sandbox','--autoplay-policy=no-user-gesture-required']});
for(const [width,height] of [[1366,900],[390,844],[360,640]]){
 const c=await b.newContext({viewport:{width,height},hasTouch:true,isMobile:width<700}),p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));p.on('response',r=>{if(r.status()>=400)report.errors.push(`${r.status()} ${r.url()}`);});await p.goto(url+'?text=school-calendars');await p.evaluate(()=>document.fonts.ready);
 const result=await p.evaluate(()=>{const r=unitReader,errors=[];let pages=0,pairs=0,targets=0;for(let t=0;t<READING.texts.length;t++){r.chooseText(t);r.setMode('parts');for(let n=0;n<r.state.count;n++){r.go(n);pages++;const text=document.querySelector('.text').getBoundingClientRect(),stage=document.querySelector('#stage').getBoundingClientRect();if(text.bottom>stage.bottom+1||text.top<stage.top)errors.push(`text does not fit: ${t}/${n}`);if(document.documentElement.scrollWidth>innerWidth+1)errors.push(`overflow ${t}/${n}`);for(const el of document.querySelectorAll('[data-he]')){el.focus();const tip=document.querySelector('#tooltip').getBoundingClientRect(),word=el.getBoundingClientRect();if(tip.left<0||tip.right>innerWidth+1)errors.push(`tooltip overflow ${t}/${n}`);if(tip.top<word.bottom&&tip.bottom>word.top)errors.push(`tooltip overlaps word ${t}/${n}`);targets++;}}r.setMode('sentences');for(let n=0;n<r.state.count;n+=2){r.go(n);const rect=()=>JSON.stringify([...document.querySelectorAll('.text .word')].map(el=>{const a=el.getBoundingClientRect();return[a.x,a.y,a.width,a.height]}));const before=rect();r.go(n+1);if(before!==rect())errors.push(`pair geometry ${t}/${n}`);pairs++;}}r.stop();return {errors,pages,pairs,targets};});report.layout.push({width,height,...result});report.errors.push(...result.errors.map(e=>`${width}: ${e}`));
 if(width===390){await p.evaluate(()=>{unitReader.chooseText(1);unitReader.setMode('parts');});const cdp=await c.newCDPSession(p);async function swipe(dx,dy){const a=await p.locator('.word').first().boundingBox(),x=Math.min(280,Math.max(110,a.x+15)),y=a.y+a.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let n=1;n<=6;n++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*n/6,y:y+dy*n/6}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
 await swipe(-80,0);assert((await p.evaluate(()=>unitReader.state.pos))===1,'left swipe');await swipe(80,0);assert((await p.evaluate(()=>unitReader.state.pos))===0,'right swipe');await p.locator('#stage').evaluate(e=>e.scrollTop=e.scrollHeight);await swipe(0,-60);assert((await p.evaluate(()=>unitReader.state.pos))===1,'up swipe');await p.locator('#stage').evaluate(e=>e.scrollTop=0);await swipe(0,60);assert((await p.evaluate(()=>unitReader.state.pos))===0,'down swipe');await p.screenshot({path:'/tmp/unit2-reader-mobile.png'});
 }await c.close();console.log('Layout',width,result.errors.length,'issues');
}
const c=await b.newContext({viewport:{width:390,height:844}}),p=await c.newPage();await p.goto(url+'?text=snow-day');await p.locator('#play').click();await p.waitForFunction(()=>!document.querySelector('#audio').paused);assert(await p.locator('#audio').evaluate(a=>a.playbackRate)===.75,'default speed');
for(const rate of ['0.25','0.75']){await p.selectOption('#speed',rate);await p.evaluate(()=>unitReader.play(true));await p.waitForTimeout(250);assert(await p.locator('#audio').evaluate(a=>a.currentTime)>0,'real playback '+rate);await p.evaluate(()=>{const a=document.querySelector('#audio'),w=unitReader.clip.words[0];a.currentTime=(w.start+w.end)/2;});await p.waitForTimeout(40);assert(await p.locator('.current').count()<=1,'single highlighted word');}
await p.evaluate(()=>{const a=document.querySelector('#audio');a.currentTime=unitReader.clip.end-.02;});await p.waitForTimeout(250);assert(await p.locator('#audio').evaluate(a=>a.paused),'stop at page end');assert(await p.evaluate(()=>unitReader.state.pos)===0,'no automatic page advance');await p.locator('#next').click();await p.waitForFunction(()=>!document.querySelector('#audio').paused);assert(await p.evaluate(()=>unitReader.state.pos)===1,'continue starts next part');await p.locator('#menuButton').click();assert(await p.locator('#audio').evaluate(a=>a.paused),'menu pauses audio');await p.locator('#closeMenu').click();
await p.reload();assert(await p.locator('#speed').inputValue()==='0.75','saved speed');
for(let t=0;t<6;t++){
 await p.evaluate(t=>{unitReader.chooseText(t);unitReader.setMode('sentences');},t);const count=await p.evaluate(()=>unitReader.state.count);
 for(let n=0;n<count;n++){
  await p.evaluate(n=>unitReader.go(n),n);const start=Date.now();await p.waitForFunction(()=>!document.querySelector('#audio').paused,{timeout:5000});const elapsed=Date.now()-start;assert(elapsed>=1700&&elapsed<5000,`two-second autoplay ${t}/${n}: ${elapsed}`);assert(await p.locator('#audio').evaluate(a=>a.readyState>=2),'decoded audio');report.autoplay++;await p.evaluate(()=>unitReader.stop());
 }console.log('Autoplay checked',report.autoplay,'slides');
}
await p.evaluate(()=>{unitReader.chooseText(0);unitReader.setMode('sentences');unitReader.go(0);unitReader.go(1);document.querySelector('#menuButton').click();});await p.waitForTimeout(2200);assert(await p.locator('#audio').evaluate(a=>a.paused),'pending autoplay cancelled by menu');
await c.close();await b.close();server.close();fs.writeFileSync(path.join(__dirname,'reading-qa-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));if(report.errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);server.close();process.exit(1)});
