/* H8 exam revision: approved full Group 01 + original Part One only. */
(async()=>{'use strict';
const $=id=>document.getElementById(id),stage=$('stage'),menu=$('menu');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,pages=[],current=0,key='',soundOn=false,timer=0,token=0,manifest=null;
const player=new Audio();player.preload='auto';
const load=async p=>{const r=await fetch(p);if(!r.ok)throw Error(p+': '+r.status);return r.json()};
const status=t=>{$('status').textContent=t};
function stop(){clearTimeout(timer);token++;player.pause();try{player.currentTime=0}catch(_){}}
function clip(){const p=pages[current];return manifest?.clips?.[p.clip]}
function speak(immediate=false){stop();const c=clip();if(!c)return;const t=token;timer=setTimeout(async()=>{if(t!==token||document.hidden)return;player.src=new URL(c.src,location.href).href;try{await player.play();if(t===token)status('קריינות AI · אנגלית')}catch(e){if(t===token&&e.name!=='AbortError')status('להשמעה לחצו ↻')}},immediate?0:2000)}
function updateSound(){const ready=!!manifest;$('sound').disabled=!ready;$('sound').setAttribute('aria-pressed',String(soundOn));$('sound').textContent=ready?(soundOn?'שמע פועל':'שמע'):'ללא שמע';$('replay').disabled=!clip()}
function fit(){stage.querySelectorAll('[data-fit]').forEach(el=>{el.style.fontSize='';let size=parseFloat(getComputedStyle(el).fontSize),child=el.firstElementChild;while(child&&(child.scrollHeight>el.clientHeight+1||child.scrollWidth>el.clientWidth+1)&&size>15){el.style.fontSize=(--size)+'px'}})}
const cell=(cls,text,phase=null,original=false)=>`<div class="cell ${cls}${phase!==null?' layer':''}" data-fit${phase!==null?` data-phase="${phase}" aria-hidden="true"`:''}${original?' data-original="true"':''}><div>${text}</div></div>`;
const meta=(text,kind='')=>`<div class="meta"><span>${esc(text)}</span><span class="kind ${kind.includes('הבנה')?'comp':''}">${esc(kind)}</span></div>`;
const section=(title,body)=>`<article class="sheet intro"><div class="pad"><div class="eyebrow">ח׳2 · הכנה למבחן הראשון</div><h1>${title}</h1><div class="rule"></div>${body}</div></article>`;
function render(p){
 if(p.type==='cover')return section('הכנה למבחן באנגלית','<h2>ח׳2</h2><p>יום חמישי, כ״ז בתשרי תשפ״ז<br><bdi dir="ltr">(8.10.2026)</bdi></p><p class="small">קבוצה 01 במלואה · החלק הראשון של הסיפור</p>');
 if(p.type==='date')return section('מועד המבחן','<h2>יום חמישי, כ״ז בתשרי תשפ״ז<br><bdi dir="ltr">(8.10.2026)</bdi></h2><p class="small">לפי לוח בית הספר, בכפוף לשינויים.</p>');
 if(p.type==='scope')return section('מה לומדים למבחן?','<p><bdi dir="ltr">Band II · Core I · Group 01</bdi><br><b>כל 55 הערכים בקבוצה הראשונה בלבד.</b></p><p><bdi dir="ltr">The Monkey Festival — Part One, A–F</bdi><br>החלק הראשון בלבד: שאלות ותרגום משפטים מעברית לאנגלית.</p><p class="small">קבוצה 02 והחלק השני של הסיפור אינם כלולים.</p>');
 if(p.type==='section')return section(p.title,`<p>${p.text}</p>${p.id==='vocab'?'<p class="small">קוראים ומנסים להבין לפני חשיפת העברית.<br>שלושה ערכים, שישה שקפים, ואז התנחתא.</p>':''}`);
 if(p.type==='word'){const w=p.w;return `<article class="sheet vocab"><div class="pad"><div class="grid">${meta('BAND II · CORE I · GROUP 01 · '+w.number+'/55',w.pos)}${cell('term',esc(w.en),null,true)}${cell('meaning',esc(w.mean_he),1)}${cell('original',esc(w.ex_en),null,true)}${cell('translation',esc(w.ex_he),1)}</div></div></article>`}
 if(p.type==='story'){const s=p.s;return `<article class="sheet reading"><div class="pad"><div class="grid">${meta('PART ONE · '+s.paragraph+' · '+s.number+'/18','קריאה')}${cell('original',s.enHtml,null,true)}${cell('translation',esc(s.he),1)}</div></div></article>`}
 if(p.type==='question'){const q=p.q;const en=esc(q.en).replace(/^(WHERE|WHAT|WHICH|WHEN|WHO|WHY|HOW)/,'<strong>$1</strong>');return `<article class="sheet qa"><div class="pad"><div class="grid">${meta('QUESTION '+q.number+' · '+q.evidence,q.level==='basic'?'שאלה בסיסית · BASIC':'שאלת הבנה · COMPREHENSION')}${cell('question',en,null,true)}${cell('qhe',esc(q.he),1)}${cell('answer',esc(q.answer),2,true)}${cell('ahe',esc(q.answerHe),3)}</div></div></article>`}
 if(p.type==='translation'){const t=p.t;return `<article class="sheet practice"><div class="pad"><div class="grid">${meta('תרגום לאנגלית · '+t.number+'/6',t.overlap?'קבוצה 01 ושפת הסיפור':'שפת הסיפור')}${cell('prompt',esc(t.he),null,true)}${cell('hint',esc(t.hint),null,true)}${cell('answer',esc(t.en),1)}</div></div></article>`}
 if(p.type==='break'){const v=BreakVisuals.get(p.number);const graphic=v.puzzle?v.art.replace('viewBox="0 0 1200 800"','viewBox="0 0 1200 560"'):v.art;return `<article class="sheet break ${v.puzzle?'diagram':''}"><div class="art">${graphic}</div><h1 class="break-title">${esc(v.titleHe)}</h1>${v.puzzle?`<button class="inspect" id="inspect" aria-pressed="false">${esc(v.button)}</button>`:''}<div class="break-caption">${meta('התנחתא · איור, לא תצלום')}${cell('original',esc(v.english),null,true)}${cell('translation',esc(v.hebrew),1)}</div></article>`}
 return section('בודקים מה כבר יודעים','<p>תרגמו שלוש מילים מקבוצה 01.<br>ענו על שאלה בסיסית ועל שאלת הבנה.<br>תרגמו משפט אחד בלי להסתכל בתשובה.</p><nav><button data-section="vocab">חזרה למילים</button><button data-section="story">חזרה לסיפור</button><button data-section="translation">חזרה לתרגום</button></nav><p class="small">אפשר לחזור לכל ערך מתפריט התוכן. אין צורך לעבור על הכול במפגש אחד.</p>');
}
const sections={};
function show(n,save=true){stop();current=Math.max(0,Math.min(pages.length-1,Number(n)||0));const p=pages[current];if(key!==p.key){stage.innerHTML=render(p);key=p.key;fit();const inspect=$('inspect');if(inspect)inspect.onclick=()=>{const card=stage.firstElementChild;const on=card.classList.toggle('measured');inspect.setAttribute('aria-pressed',String(on))};stage.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>show(sections[b.dataset.section]));}stage.querySelectorAll('[data-phase]').forEach(el=>{let visible=p.phase>=Number(el.dataset.phase);el.classList.toggle('visible',visible);el.setAttribute('aria-hidden',String(!visible))});
 $('counter').textContent=`${current+1} / ${pages.length}`;$('progress').style.width=((current+1)/pages.length*100)+'%';document.querySelectorAll('[data-step]').forEach(b=>{b.disabled=Number(b.dataset.step)<0?current===0:current===pages.length-1});
 status(p.type==='question'?(p.phase<2?'ענו בעצמכם לפני חשיפת התשובה.':'תשובה אפשרית — אפשר לנסח גם אחרת.'):p.phase===0&&['word','story','break'].includes(p.type)?'בשקף הבא נחשף התרגום, בלי להזיז את האנגלית.':'סווייפ למעלה / שמאלה: קדימה · למטה / ימינה: אחורה');
 if(save){history.replaceState(null,'','#slide-'+(current+1));try{localStorage.setItem('teachers-h8-exam1-approved',String(current))}catch(_){}}
 updateSound();if(soundOn&&p.phase===0&&clip())speak();
}
function move(d){if(!menu.open)show(current+d)}
function addPair(p){pages.push({...p,phase:0},{...p,phase:1})}
function listItems(){const term=$('search').value.trim().toLowerCase();$('items').innerHTML=pages.map((p,i)=>({p,i})).filter(({p})=>p.phase===0&&['word','story','question'].includes(p.type)).filter(({p})=>(p.w?.en||p.s?.plain||p.q?.en||'').toLowerCase().includes(term)).map(({p,i})=>`<button data-page="${i}"><small>${p.type==='word'?'01.'+p.w.number:p.type==='story'?'פסקה '+p.s.paragraph:'שאלה '+p.q.number}</small>${esc(p.w?.en||p.s?.plain||p.q?.en)}</button>`).join('')}
$('items').onclick=e=>{const b=e.target.closest('[data-page]');if(b){menu.close();show(Number(b.dataset.page))}};$('search').oninput=listItems;
$('contents').onclick=()=>{stop();menu.showModal()};document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{menu.close();show(sections[b.dataset.section])});document.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>move(Number(b.dataset.step)));
$('sound').onclick=()=>{soundOn=!soundOn;updateSound();if(soundOn&&clip())speak(true);else stop()};$('replay').onclick=()=>speak(true);
$('motion').onclick=()=>{const off=document.body.classList.toggle('no-motion');$('motion').setAttribute('aria-pressed',String(!off))};$('full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch(_){}};
window.addEventListener('keydown',e=>{if(menu.open||e.target.closest('input,textarea,select')||e.ctrlKey||e.metaKey||e.altKey)return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();move(1)}else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();move(-1)}else if(e.key==='Home'){e.preventDefault();show(0)}else if(e.key==='End'){e.preventDefault();show(pages.length-1)}else if(e.key.toLowerCase()==='r')speak(true)});
let gesture=null,active=new Set();const ignored=t=>t.closest('button,a,input,select');
if('PointerEvent'in window){stage.addEventListener('pointerdown',e=>{active.add(e.pointerId);if(active.size>1){gesture=null;return}if(ignored(e.target)||e.pointerType==='mouse'&&e.button!==0)return;gesture={id:e.pointerId,x:e.clientX,y:e.clientY,t:Date.now()};try{stage.setPointerCapture(e.pointerId)}catch(_){}});stage.addEventListener('pointerup',e=>{active.delete(e.pointerId);const g=gesture;gesture=null;if(!g||g.id!==e.pointerId||active.size)return;const dx=e.clientX-g.x,dy=e.clientY-g.y;if(Math.max(Math.abs(dx),Math.abs(dy))>=44&&Date.now()-g.t<1800)move((Math.abs(dx)>Math.abs(dy)?dx:dy)<0?1:-1)});stage.addEventListener('pointercancel',e=>{active.delete(e.pointerId);gesture=null})}else{stage.addEventListener('touchstart',e=>{gesture=e.touches.length===1&&!ignored(e.target)?{x:e.touches[0].clientX,y:e.touches[0].clientY}:null},{passive:true});stage.addEventListener('touchmove',e=>{if(e.touches.length!==1)gesture=null;else if(gesture)e.preventDefault()},{passive:false});stage.addEventListener('touchend',e=>{const g=gesture;gesture=null;if(!g||e.touches.length)return;const t=e.changedTouches[0],dx=t.clientX-g.x,dy=t.clientY-g.y;if(Math.max(Math.abs(dx),Math.abs(dy))>=44)move((Math.abs(dx)>Math.abs(dy)?dx:dy)<0?1:-1)},{passive:true});stage.addEventListener('touchcancel',()=>gesture=null)}
let sum=0,last=0,lock=0;stage.addEventListener('wheel',e=>{if(e.ctrlKey||menu.open)return;e.preventDefault();const now=performance.now();if(now<lock)return;if(now-last>180)sum=0;last=now;sum+=(Math.abs(e.deltaY)>Math.abs(e.deltaX)?e.deltaY:e.deltaX)*(e.deltaMode===1?16:1);if(Math.abs(sum)>55){move(sum>0?1:-1);sum=0;lock=now+450}},{passive:false});
window.addEventListener('resize',fit);window.addEventListener('pagehide',stop);window.addEventListener('blur',stop);document.addEventListener('visibilitychange',()=>{if(document.hidden)stop()});document.addEventListener('click',e=>{if(e.target.closest('a'))stop()});
try{data=await load('lesson.json?v=20260917-approved1');if(data.words.length!==55||data.story.length!==18)throw Error('Incomplete source');pages=[{type:'cover',key:'cover'},{type:'date',key:'date'},{type:'scope',key:'scope'}];sections.start=0;sections.vocab=pages.length;pages.push({type:'section',key:'vocab',id:'vocab',title:'אוצר מילים — קבוצה 01',text:'כל 55 הערכים של הקבוצה הראשונה.'});data.words.forEach((w,i)=>{addPair({type:'word',key:w.id,w,clip:w.id});if((i+1)%3===0)addPair({type:'break',key:'vb'+i,number:Math.floor(i/3),group:'vocab'})});sections.story=pages.length;pages.push({type:'section',key:'story',title:'החלק הראשון של הסיפור',text:'The Monkey Festival · Part One · A–F<br>כל משפט באנגלית, ואחריו התרגום.'});data.story.forEach((s,i)=>{addPair({type:'story',key:s.id,s,clip:s.id});data.questions.filter(q=>q.after===i+1).forEach(q=>{for(let phase=0;phase<4;phase++)pages.push({type:'question',key:'q'+q.number,q,phase})});if([4,11,18].includes(i+1))addPair({type:'break',key:'sb'+i,number:18+[4,11,18].indexOf(i+1),group:'story'})});sections.translation=pages.length;pages.push({type:'section',key:'translation',title:'מעברית לאנגלית',text:'כותבים משפט שלם, ואז משווים לתשובה אפשרית.<br>אלה משפטי תרגול, לא נוסח מובטח של שאלות המבחן.'});data.translations.forEach(t=>addPair({type:'translation',key:'t'+t.number,t}));pages.push({type:'end',key:'end'});listItems();const hash=location.hash.match(/^#slide-(\d+)$/);show(hash?Number(hash[1])-1:0,false);document.fonts?.ready.then(fit);manifest=await load('audio-manifest.json?v=20260917-approved1');if(manifest.count!==73||!data.words.concat(data.story).every(x=>manifest.clips[x.id]))throw Error('Incomplete narration');updateSound();window.ExamDeck={pages,data,show,move,get current(){return current},get player(){return player},get ready(){return!!manifest}};
}catch(e){console.error(e);status('חלק מהקבצים לא נטענו. יש לרענן את הדף.');if(!pages.length)stage.innerHTML='<p class="loading">המצגת לא נטענה. יש לרענן את הדף ולבדוק את החיבור.</p>';updateSound()}
})();
